INSERT INTO IT_EntityFieldProductionType VALUES (1,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',114);
INSERT INTO IT_EntityFieldProductionType VALUES (2,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',115);
INSERT INTO IT_EntityFieldProductionType VALUES (3,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',116);
INSERT INTO IT_EntityFieldProductionType VALUES (4,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',117);
INSERT INTO IT_EntityFieldProductionType VALUES (5,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',118);
INSERT INTO IT_EntityFieldProductionType VALUES (6,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',119);
INSERT INTO IT_EntityFieldProductionType VALUES (7,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',120);
INSERT INTO IT_EntityFieldProductionType VALUES (8,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',121);
INSERT INTO IT_EntityFieldProductionType VALUES (9,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',122);
INSERT INTO IT_EntityFieldProductionType VALUES (10,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',123);
INSERT INTO IT_EntityFieldProductionType VALUES (11,NOW(),1,0,NOW(),'','Generic','Generic',124);
INSERT INTO IT_EntityFieldProductionType VALUES (12,NOW(),1,0,NOW(),'','Generic','Generic',125);
INSERT INTO IT_EntityFieldProductionType VALUES (13,NOW(),1,0,NOW(),'','Generic','Generic',126);
INSERT INTO IT_EntityFieldProductionType VALUES (14,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',127);
INSERT INTO IT_EntityFieldProductionType VALUES (15,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',128);
INSERT INTO IT_EntityFieldProductionType VALUES (16,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',129);
INSERT INTO IT_EntityFieldProductionType VALUES (17,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',130);
INSERT INTO IT_EntityFieldProductionType VALUES (18,NOW(),1,0,NOW(),'','Generic','Generic',131);
INSERT INTO IT_EntityFieldProductionType VALUES (19,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',132);
INSERT INTO IT_EntityFieldProductionType VALUES (20,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',133);
INSERT INTO IT_EntityFieldProductionType VALUES (21,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',134);
INSERT INTO IT_EntityFieldProductionType VALUES (22,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',135);
INSERT INTO IT_EntityFieldProductionType VALUES (23,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',136);
INSERT INTO IT_EntityFieldProductionType VALUES (24,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',137);
INSERT INTO IT_EntityFieldProductionType VALUES (25,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',138);
INSERT INTO IT_EntityFieldProductionType VALUES (26,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',139);
INSERT INTO IT_EntityFieldProductionType VALUES (27,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',140);
INSERT INTO IT_EntityFieldProductionType VALUES (28,NOW(),1,0,NOW(),'','Generic','Generic',141);
INSERT INTO IT_EntityFieldProductionType VALUES (29,NOW(),1,0,NOW(),'','Generic','Generic',142);
INSERT INTO IT_EntityFieldProductionType VALUES (30,NOW(),1,0,NOW(),'','Generic','Generic',143);
INSERT INTO IT_EntityFieldProductionType VALUES (31,NOW(),1,0,NOW(),'','Generic','Generic',144);
INSERT INTO IT_EntityFieldProductionType VALUES (32,NOW(),1,0,NOW(),'','Generic','Generic',145);
INSERT INTO IT_EntityFieldProductionType VALUES (33,NOW(),1,0,NOW(),'','Generic','Generic',146);
INSERT INTO IT_EntityFieldProductionType VALUES (34,NOW(),1,0,NOW(),'','Generic','Generic',147);
INSERT INTO IT_EntityFieldProductionType VALUES (35,NOW(),1,0,NOW(),'','Generic','Generic',148);
INSERT INTO IT_EntityFieldProductionType VALUES (36,NOW(),1,0,NOW(),'','Generic','Generic',149);
INSERT INTO IT_EntityFieldProductionType VALUES (37,NOW(),1,0,NOW(),'','Generic','Generic',150);
INSERT INTO IT_EntityFieldProductionType VALUES (38,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',341);
INSERT INTO IT_EntityFieldProductionType VALUES (39,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',342);
INSERT INTO IT_EntityFieldProductionType VALUES (40,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',343);
INSERT INTO IT_EntityFieldProductionType VALUES (41,NOW(),1,0,NOW(),'','Generic','Generic',344);
INSERT INTO IT_EntityFieldProductionType VALUES (42,NOW(),1,0,NOW(),'','Generic','Generic',345);
INSERT INTO IT_EntityFieldProductionType VALUES (43,NOW(),1,0,NOW(),'','Generic','Generic',346);
INSERT INTO IT_EntityFieldProductionType VALUES (44,NOW(),1,0,NOW(),'','Generic','Generic',347);
INSERT INTO IT_EntityFieldProductionType VALUES (45,NOW(),1,0,NOW(),'','Generic','Generic',348);
INSERT INTO IT_EntityFieldProductionType VALUES (46,NOW(),1,0,NOW(),'','Generic','Generic',516);
INSERT INTO IT_EntityFieldProductionType VALUES (47,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',517);
INSERT INTO IT_EntityFieldProductionType VALUES (48,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',518);
INSERT INTO IT_EntityFieldProductionType VALUES (49,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',519);
INSERT INTO IT_EntityFieldProductionType VALUES (50,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',520);
INSERT INTO IT_EntityFieldProductionType VALUES (51,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',521);
INSERT INTO IT_EntityFieldProductionType VALUES (52,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',522);
INSERT INTO IT_EntityFieldProductionType VALUES (53,NOW(),1,0,NOW(),'','Generic','Generic',523);
INSERT INTO IT_EntityFieldProductionType VALUES (54,NOW(),1,0,NOW(),'','Generic','Generic',524);
INSERT INTO IT_EntityFieldProductionType VALUES (55,NOW(),1,0,NOW(),'','Generic','Generic',525);
INSERT INTO IT_EntityFieldProductionType VALUES (56,NOW(),1,0,NOW(),'','Generic','Generic',526);
INSERT INTO IT_EntityFieldProductionType VALUES (57,NOW(),1,0,NOW(),'','Generic','Generic',527);
INSERT INTO IT_EntityFieldProductionType VALUES (58,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',528);
INSERT INTO IT_EntityFieldProductionType VALUES (59,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',529);
INSERT INTO IT_EntityFieldProductionType VALUES (60,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',530);
INSERT INTO IT_EntityFieldProductionType VALUES (61,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',531);
INSERT INTO IT_EntityFieldProductionType VALUES (62,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',532);
INSERT INTO IT_EntityFieldProductionType VALUES (63,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',533);
INSERT INTO IT_EntityFieldProductionType VALUES (64,NOW(),1,0,NOW(),'','Generic','Generic',534);
INSERT INTO IT_EntityFieldProductionType VALUES (65,NOW(),1,0,NOW(),'','Generic','Generic',535);
INSERT INTO IT_EntityFieldProductionType VALUES (66,NOW(),1,0,NOW(),'','Generic','Generic',536);
INSERT INTO IT_EntityFieldProductionType VALUES (67,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',537);
INSERT INTO IT_EntityFieldProductionType VALUES (68,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',538);
INSERT INTO IT_EntityFieldProductionType VALUES (69,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',539);
INSERT INTO IT_EntityFieldProductionType VALUES (70,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',540);
INSERT INTO IT_EntityFieldProductionType VALUES (71,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',541);
INSERT INTO IT_EntityFieldProductionType VALUES (72,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',542);
INSERT INTO IT_EntityFieldProductionType VALUES (73,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',543);
INSERT INTO IT_EntityFieldProductionType VALUES (74,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',544);
INSERT INTO IT_EntityFieldProductionType VALUES (75,NOW(),1,0,NOW(),'','Generic','Generic',545);
INSERT INTO IT_EntityFieldProductionType VALUES (76,NOW(),1,0,NOW(),'','Generic','Generic',546);
INSERT INTO IT_EntityFieldProductionType VALUES (77,NOW(),1,0,NOW(),'Estructura Organizativa','Generic','Generic',670);
INSERT INTO IT_EntityFieldProductionType VALUES (78,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',671);
INSERT INTO IT_EntityFieldProductionType VALUES (79,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',672);
INSERT INTO IT_EntityFieldProductionType VALUES (80,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',673);
INSERT INTO IT_EntityFieldProductionType VALUES (81,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',674);
INSERT INTO IT_EntityFieldProductionType VALUES (82,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',675);
INSERT INTO IT_EntityFieldProductionType VALUES (83,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',676);
INSERT INTO IT_EntityFieldProductionType VALUES (84,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',677);
INSERT INTO IT_EntityFieldProductionType VALUES (85,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',678);
INSERT INTO IT_EntityFieldProductionType VALUES (86,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',679);
INSERT INTO IT_EntityFieldProductionType VALUES (87,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',680);
INSERT INTO IT_EntityFieldProductionType VALUES (88,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',681);
INSERT INTO IT_EntityFieldProductionType VALUES (89,NOW(),1,0,NOW(),'','Generic','Generic',682);
INSERT INTO IT_EntityFieldProductionType VALUES (90,NOW(),1,0,NOW(),'','Generic','Generic',683);
INSERT INTO IT_EntityFieldProductionType VALUES (91,NOW(),1,0,NOW(),'','Generic','Generic',684);
INSERT INTO IT_EntityFieldProductionType VALUES (92,NOW(),1,0,NOW(),'','Generic','Generic',685);
INSERT INTO IT_EntityFieldProductionType VALUES (93,NOW(),1,0,NOW(),'','Generic','Generic',686);
INSERT INTO IT_EntityFieldProductionType VALUES (94,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',687);
INSERT INTO IT_EntityFieldProductionType VALUES (95,NOW(),1,0,NOW(),'','Generic','Generic',688);
INSERT INTO IT_EntityFieldProductionType VALUES (96,NOW(),1,0,NOW(),'','Generic','Generic',689);
INSERT INTO IT_EntityFieldProductionType VALUES (97,NOW(),1,0,NOW(),'','Generic','Generic',690);
INSERT INTO IT_EntityFieldProductionType VALUES (98,NOW(),1,0,NOW(),'','Generic','Generic',691);
INSERT INTO IT_EntityFieldProductionType VALUES (99,NOW(),1,0,NOW(),'','Generic','Generic',692);
INSERT INTO IT_EntityFieldProductionType VALUES (100,NOW(),1,0,NOW(),'','Generic','Generic',693);
INSERT INTO IT_EntityFieldProductionType VALUES (101,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',694);
INSERT INTO IT_EntityFieldProductionType VALUES (102,NOW(),1,0,NOW(),'','Generic','Generic',695);
INSERT INTO IT_EntityFieldProductionType VALUES (103,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',696);
INSERT INTO IT_EntityFieldProductionType VALUES (104,NOW(),1,0,NOW(),'','Generic','Generic',697);
INSERT INTO IT_EntityFieldProductionType VALUES (105,NOW(),1,0,NOW(),'','Generic','Generic',698);
INSERT INTO IT_EntityFieldProductionType VALUES (106,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',699);
INSERT INTO IT_EntityFieldProductionType VALUES (107,NOW(),1,0,NOW(),'','Generic','Generic',700);
INSERT INTO IT_EntityFieldProductionType VALUES (108,NOW(),1,0,NOW(),'','Generic','Generic',701);
INSERT INTO IT_EntityFieldProductionType VALUES (109,NOW(),1,0,NOW(),'','Generic','Generic',881);
INSERT INTO IT_EntityFieldProductionType VALUES (110,NOW(),1,0,NOW(),'','Generic','Generic',882);
INSERT INTO IT_EntityFieldProductionType VALUES (111,NOW(),1,0,NOW(),'','Generic','Generic',883);
INSERT INTO IT_EntityFieldProductionType VALUES (112,NOW(),1,0,NOW(),'','Generic','Generic',884);
INSERT INTO IT_EntityFieldProductionType VALUES (113,NOW(),1,0,NOW(),'','Generic','Generic',885);
INSERT INTO IT_EntityFieldProductionType VALUES (114,NOW(),1,0,NOW(),'','Generic','Generic',886);
INSERT INTO IT_EntityFieldProductionType VALUES (115,NOW(),1,0,NOW(),'','Generic','Generic',887);
INSERT INTO IT_EntityFieldProductionType VALUES (116,NOW(),1,0,NOW(),'','Generic','Generic',888);
INSERT INTO IT_EntityFieldProductionType VALUES (117,NOW(),1,0,NOW(),'','Generic','Generic',889);
INSERT INTO IT_EntityFieldProductionType VALUES (118,NOW(),1,0,NOW(),'','Generic','Generic',890);
INSERT INTO IT_EntityFieldProductionType VALUES (119,NOW(),1,0,NOW(),'','Generic','Generic',891);
INSERT INTO IT_EntityFieldProductionType VALUES (120,NOW(),1,0,NOW(),'','Generic','Generic',892);
INSERT INTO IT_EntityFieldProductionType VALUES (121,NOW(),1,0,NOW(),'','Generic','Generic',893);
INSERT INTO IT_EntityFieldProductionType VALUES (122,NOW(),1,0,NOW(),'','Generic','Generic',894);
INSERT INTO IT_EntityFieldProductionType VALUES (123,NOW(),1,0,NOW(),'','Generic','Generic',895);
INSERT INTO IT_EntityFieldProductionType VALUES (124,NOW(),1,0,NOW(),'','Generic','Generic',896);
INSERT INTO IT_EntityFieldProductionType VALUES (125,NOW(),1,0,NOW(),'','Generic','Generic',897);
INSERT INTO IT_EntityFieldProductionType VALUES (126,NOW(),1,0,NOW(),'','Generic','Generic',898);
INSERT INTO IT_EntityFieldProductionType VALUES (127,NOW(),1,0,NOW(),'','Generic','Generic',899);
INSERT INTO IT_EntityFieldProductionType VALUES (128,NOW(),1,0,NOW(),'','Generic','Generic',900);
INSERT INTO IT_EntityFieldProductionType VALUES (129,NOW(),1,0,NOW(),'','Generic','Generic',901);
INSERT INTO IT_EntityFieldProductionType VALUES (130,NOW(),1,0,NOW(),'','Generic','Generic',902);
INSERT INTO IT_EntityFieldProductionType VALUES (131,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1115);
INSERT INTO IT_EntityFieldProductionType VALUES (132,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1116);
INSERT INTO IT_EntityFieldProductionType VALUES (133,NOW(),1,0,NOW(),'','Generic','Generic',1117);
INSERT INTO IT_EntityFieldProductionType VALUES (134,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1118);
INSERT INTO IT_EntityFieldProductionType VALUES (135,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1119);
INSERT INTO IT_EntityFieldProductionType VALUES (136,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1120);
INSERT INTO IT_EntityFieldProductionType VALUES (137,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1121);
INSERT INTO IT_EntityFieldProductionType VALUES (138,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1122);
INSERT INTO IT_EntityFieldProductionType VALUES (139,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1123);
INSERT INTO IT_EntityFieldProductionType VALUES (140,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1124);
INSERT INTO IT_EntityFieldProductionType VALUES (141,NOW(),1,0,NOW(),'','Generic','Generic',1125);
INSERT INTO IT_EntityFieldProductionType VALUES (142,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1126);
INSERT INTO IT_EntityFieldProductionType VALUES (143,NOW(),1,0,NOW(),'','Generic','Generic',1127);
INSERT INTO IT_EntityFieldProductionType VALUES (144,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1128);
INSERT INTO IT_EntityFieldProductionType VALUES (145,NOW(),1,0,NOW(),'','Generic','Generic',1129);
INSERT INTO IT_EntityFieldProductionType VALUES (146,NOW(),1,0,NOW(),'','Generic','Generic',1130);
INSERT INTO IT_EntityFieldProductionType VALUES (147,NOW(),1,0,NOW(),'','Generic','Generic',1131);
INSERT INTO IT_EntityFieldProductionType VALUES (148,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1132);
INSERT INTO IT_EntityFieldProductionType VALUES (149,NOW(),1,0,NOW(),'','Generic','Generic',1133);
INSERT INTO IT_EntityFieldProductionType VALUES (150,NOW(),1,0,NOW(),'','Generic','Generic',1134);
INSERT INTO IT_EntityFieldProductionType VALUES (151,NOW(),1,0,NOW(),'','Generic','Generic',1135);
INSERT INTO IT_EntityFieldProductionType VALUES (152,NOW(),1,0,NOW(),'','Generic','Generic',1136);
INSERT INTO IT_EntityFieldProductionType VALUES (153,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1137);
INSERT INTO IT_EntityFieldProductionType VALUES (154,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1138);
INSERT INTO IT_EntityFieldProductionType VALUES (155,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1139);
INSERT INTO IT_EntityFieldProductionType VALUES (156,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1140);
INSERT INTO IT_EntityFieldProductionType VALUES (157,NOW(),1,0,NOW(),'','Generic','Generic',1141);
INSERT INTO IT_EntityFieldProductionType VALUES (158,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1142);
INSERT INTO IT_EntityFieldProductionType VALUES (159,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1143);
INSERT INTO IT_EntityFieldProductionType VALUES (160,NOW(),1,0,NOW(),'','Generic','Generic',1144);
INSERT INTO IT_EntityFieldProductionType VALUES (161,NOW(),1,0,NOW(),'','Generic','Generic',1145);
INSERT INTO IT_EntityFieldProductionType VALUES (162,NOW(),1,0,NOW(),'','Generic','Generic',1146);
INSERT INTO IT_EntityFieldProductionType VALUES (163,NOW(),1,0,NOW(),'','Generic','Generic',1147);
INSERT INTO IT_EntityFieldProductionType VALUES (164,NOW(),1,0,NOW(),'','Generic','Generic',1148);
INSERT INTO IT_EntityFieldProductionType VALUES (165,NOW(),1,0,NOW(),'','Generic','Generic',1149);
INSERT INTO IT_EntityFieldProductionType VALUES (166,NOW(),1,0,NOW(),'','Generic','Generic',1150);
INSERT INTO IT_EntityFieldProductionType VALUES (167,NOW(),1,0,NOW(),'','Generic','Generic',1151);
INSERT INTO IT_EntityFieldProductionType VALUES (168,NOW(),1,0,NOW(),'','Generic','Generic',1152);
INSERT INTO IT_EntityFieldProductionType VALUES (169,NOW(),1,0,NOW(),'','Generic','Generic',1153);
INSERT INTO IT_EntityFieldProductionType VALUES (170,NOW(),1,0,NOW(),'','Generic','Generic',1154);
INSERT INTO IT_EntityFieldProductionType VALUES (171,NOW(),1,0,NOW(),'','Generic','Generic',1155);
INSERT INTO IT_EntityFieldProductionType VALUES (172,NOW(),1,0,NOW(),'','Generic','Generic',1156);
INSERT INTO IT_EntityFieldProductionType VALUES (173,NOW(),1,0,NOW(),'','Generic','Generic',1157);
INSERT INTO IT_EntityFieldProductionType VALUES (174,NOW(),1,0,NOW(),'','Generic','Generic',1158);
INSERT INTO IT_EntityFieldProductionType VALUES (175,NOW(),1,0,NOW(),'','Generic','Generic',1159);
INSERT INTO IT_EntityFieldProductionType VALUES (176,NOW(),1,0,NOW(),'','Generic','Generic',1160);
INSERT INTO IT_EntityFieldProductionType VALUES (177,NOW(),1,0,NOW(),'','Generic','Generic',1161);
INSERT INTO IT_EntityFieldProductionType VALUES (178,NOW(),1,0,NOW(),'','Generic','Generic',1162);
INSERT INTO IT_EntityFieldProductionType VALUES (179,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1399);
INSERT INTO IT_EntityFieldProductionType VALUES (180,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1400);
INSERT INTO IT_EntityFieldProductionType VALUES (181,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1401);
INSERT INTO IT_EntityFieldProductionType VALUES (182,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1402);
INSERT INTO IT_EntityFieldProductionType VALUES (183,NOW(),1,0,NOW(),'','Generic','Generic',1403);
INSERT INTO IT_EntityFieldProductionType VALUES (184,NOW(),1,0,NOW(),'Estructura Organizativa','Generic','Generic',1404);
INSERT INTO IT_EntityFieldProductionType VALUES (185,NOW(),1,0,NOW(),'Interlocutores','Generic','Generic',1405);
INSERT INTO IT_EntityFieldProductionType VALUES (186,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1406);
INSERT INTO IT_EntityFieldProductionType VALUES (187,NOW(),1,0,NOW(),'','Generic','Generic',1407);
INSERT INTO IT_EntityFieldProductionType VALUES (188,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1408);
INSERT INTO IT_EntityFieldProductionType VALUES (189,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1409);
INSERT INTO IT_EntityFieldProductionType VALUES (190,NOW(),1,0,NOW(),'','Generic','Generic',1410);
INSERT INTO IT_EntityFieldProductionType VALUES (191,NOW(),1,0,NOW(),'','Generic','Generic',1411);
INSERT INTO IT_EntityFieldProductionType VALUES (192,NOW(),1,0,NOW(),'','Generic','Generic',1412);
INSERT INTO IT_EntityFieldProductionType VALUES (193,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1413);
INSERT INTO IT_EntityFieldProductionType VALUES (194,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1414);
INSERT INTO IT_EntityFieldProductionType VALUES (195,NOW(),1,0,NOW(),'','Generic','Generic',1415);
INSERT INTO IT_EntityFieldProductionType VALUES (196,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1416);
INSERT INTO IT_EntityFieldProductionType VALUES (197,NOW(),1,0,NOW(),'','Generic','Generic',1417);
INSERT INTO IT_EntityFieldProductionType VALUES (198,NOW(),1,0,NOW(),'','Generic','Generic',1418);
INSERT INTO IT_EntityFieldProductionType VALUES (199,NOW(),1,0,NOW(),'Datos de ventas','Generic','Generic',1419);
INSERT INTO IT_EntityFieldProductionType VALUES (200,NOW(),1,0,NOW(),'','Generic','Generic',1420);
INSERT INTO IT_EntityFieldProductionType VALUES (201,NOW(),1,0,NOW(),'','Generic','Generic',1421);
INSERT INTO IT_EntityFieldProductionType VALUES (202,NOW(),1,0,NOW(),'Estructura Organizativa','Generic','Generic',1422);
INSERT INTO IT_EntityFieldProductionType VALUES (203,NOW(),1,0,NOW(),'','Generic','Generic',1423);
INSERT INTO IT_EntityFieldProductionType VALUES (204,NOW(),1,0,NOW(),'','Generic','Generic',1424);
INSERT INTO IT_EntityFieldProductionType VALUES (205,NOW(),1,0,NOW(),'','Generic','Generic',1425);
INSERT INTO IT_EntityFieldProductionType VALUES (206,NOW(),1,0,NOW(),'','Generic','Generic',1426);
INSERT INTO IT_EntityFieldProductionType VALUES (207,NOW(),1,0,NOW(),'','Generic','Generic',1427);
INSERT INTO IT_EntityFieldProductionType VALUES (208,NOW(),1,0,NOW(),'','Generic','Generic',1428);
INSERT INTO IT_EntityFieldProductionType VALUES (209,NOW(),1,0,NOW(),'','Generic','Generic',1429);
INSERT INTO IT_EntityFieldProductionType VALUES (210,NOW(),1,0,NOW(),'','Generic','Generic',1430);
INSERT INTO IT_EntityFieldProductionType VALUES (211,NOW(),1,0,NOW(),'','Generic','Generic',1431);
INSERT INTO IT_EntityFieldProductionType VALUES (212,NOW(),1,0,NOW(),'','Generic','Generic',1432);
INSERT INTO IT_EntityFieldProductionType VALUES (213,NOW(),1,0,NOW(),'','Generic','Generic',1433);
INSERT INTO IT_EntityFieldProductionType VALUES (214,NOW(),1,0,NOW(),'Estructura Organizativa','Generic','Generic',1434);
INSERT INTO IT_EntityFieldProductionType VALUES (215,NOW(),1,0,NOW(),'','Generic','Generic',1435);
INSERT INTO IT_EntityFieldProductionType VALUES (216,NOW(),1,0,NOW(),'','Generic','Generic',1436);
INSERT INTO IT_EntityFieldProductionType VALUES (217,NOW(),1,0,NOW(),'','Generic','Generic',1437);
INSERT INTO IT_EntityFieldProductionType VALUES (218,NOW(),1,0,NOW(),'','Generic','Generic',1438);
INSERT INTO IT_EntityFieldProductionType VALUES (219,NOW(),1,0,NOW(),'','Generic','Generic',1439);
INSERT INTO IT_EntityFieldProductionType VALUES (220,NOW(),1,0,NOW(),'','Generic','Generic',1440);
INSERT INTO IT_EntityFieldProductionType VALUES (221,NOW(),1,0,NOW(),'','Generic','Generic',1441);
INSERT INTO IT_EntityFieldProductionType VALUES (222,NOW(),1,0,NOW(),'','Generic','Generic',1442);
INSERT INTO IT_EntityFieldProductionType VALUES (223,NOW(),1,0,NOW(),'','Generic','Generic',1443);
INSERT INTO IT_EntityFieldProductionType VALUES (224,NOW(),1,0,NOW(),'','Generic','Generic',1444);
INSERT INTO IT_EntityFieldProductionType VALUES (225,NOW(),1,0,NOW(),'','Generic','Generic',1445);
INSERT INTO IT_EntityFieldProductionType VALUES (226,NOW(),1,0,NOW(),'','Generic','Generic',1632);
INSERT INTO IT_EntityFieldProductionType VALUES (227,NOW(),1,0,NOW(),'','Generic','Generic',1633);
INSERT INTO IT_EntityFieldProductionType VALUES (228,NOW(),1,0,NOW(),'','Generic','Generic',1634);
INSERT INTO IT_EntityFieldProductionType VALUES (229,NOW(),1,0,NOW(),'','Generic','Generic',1635);
INSERT INTO IT_EntityFieldProductionType VALUES (230,NOW(),1,0,NOW(),'','Generic','Generic',1636);
INSERT INTO IT_EntityFieldProductionType VALUES (231,NOW(),1,0,NOW(),'','Generic','Generic',1637);
INSERT INTO IT_EntityFieldProductionType VALUES (232,NOW(),1,0,NOW(),'','Generic','Generic',1638);
INSERT INTO IT_EntityFieldProductionType VALUES (233,NOW(),1,0,NOW(),'','Generic','Generic',1639);
INSERT INTO IT_EntityFieldProductionType VALUES (234,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1640);
INSERT INTO IT_EntityFieldProductionType VALUES (235,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1641);
INSERT INTO IT_EntityFieldProductionType VALUES (236,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1642);
INSERT INTO IT_EntityFieldProductionType VALUES (237,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1643);
INSERT INTO IT_EntityFieldProductionType VALUES (238,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',1644);
INSERT INTO IT_EntityFieldProductionType VALUES (239,NOW(),1,0,NOW(),'','Generic','Generic',1645);
INSERT INTO IT_EntityFieldProductionType VALUES (240,NOW(),1,0,NOW(),'','Generic','Generic',1646);
INSERT INTO IT_EntityFieldProductionType VALUES (241,NOW(),1,0,NOW(),'','Generic','Generic',1647);
INSERT INTO IT_EntityFieldProductionType VALUES (242,NOW(),1,0,NOW(),'','Generic','Generic',1648);
INSERT INTO IT_EntityFieldProductionType VALUES (243,NOW(),1,0,NOW(),'','Generic','Generic',1649);
INSERT INTO IT_EntityFieldProductionType VALUES (244,NOW(),1,0,NOW(),'','Generic','Generic',2625);
INSERT INTO IT_EntityFieldProductionType VALUES (245,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',2626);
INSERT INTO IT_EntityFieldProductionType VALUES (246,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',2627);
INSERT INTO IT_EntityFieldProductionType VALUES (247,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',2628);
INSERT INTO IT_EntityFieldProductionType VALUES (248,NOW(),1,0,NOW(),'','Generic','Generic',2629);
INSERT INTO IT_EntityFieldProductionType VALUES (249,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',2630);
INSERT INTO IT_EntityFieldProductionType VALUES (250,NOW(),1,0,NOW(),'Datos Productivos','Generic','Generic',2631);
