INSERT INTO IT_EntityListNameText VALUES (1,'es', NOW(), 1, 0, NOW(),'Interlocutores',1,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (2,'es', NOW(), 1, 0, NOW(),'Textos de entidades',2,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (3,'es', NOW(), 1, 0, NOW(),'Grupos de estados',3,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (4,'es', NOW(), 1, 0, NOW(),'Tipos de documentos SAP',4,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (5,'es', NOW(), 1, 0, NOW(),'Tipología de facturación',5,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (6,'es', NOW(), 1, 0, NOW(),'Mensajes',6,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (7,'es', NOW(), 1, 0, NOW(),'',7,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (8,'es', NOW(), 1, 0, NOW(),'Reglas de pre-facturación',8,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (9,'es', NOW(), 1, 0, NOW(),'Interlocutores de la posición',9,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (10,'es', NOW(), 1, 0, NOW(),'Textos de la solicitud',10,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (11,'es', NOW(), 1, 0, NOW(),'Interlocutores de la petición',11,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (12,'es', NOW(), 1, 0, NOW(),'Precio de la petición',12,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (13,'es', NOW(), 1, 0, NOW(),'Textos de canal de distribución',13,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (14,'es', NOW(), 1, 0, NOW(),'Compañias',14,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (15,'es', NOW(), 1, 0, NOW(),'Textos de grupos de estados',15,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (16,'es', NOW(), 1, 0, NOW(),'Textos de impuestos',16,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (17,'es', NOW(), 1, 0, NOW(),'Textos de sistemas lims',17,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (18,'es', NOW(), 1, 0, NOW(),'Tipología de facturación',18,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (19,'es', NOW(), 1, 0, NOW(),'Textos de unidades',19,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (20,'es', NOW(), 1, 0, NOW(),'Clasificación',20,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (21,'es', NOW(), 1, 0, NOW(),'Estado de la solicitud',21,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (22,'es', NOW(), 1, 0, NOW(),'Polizas de capitativo',22,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (23,'es', NOW(), 1, 0, NOW(),'Bloqueos de cortesía',23,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (24,'es', NOW(), 1, 0, NOW(),'Configuración de campos',24,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (25,'es', NOW(), 1, 0, NOW(),'Nombre de campos',25,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (26,'es', NOW(), 1, 0, NOW(),'Textos de campos',26,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (27,'es', NOW(), 1, 0, NOW(),'Log de facturación',27,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (28,'es', NOW(), 1, 0, NOW(),'Secuencias de determinación de incongruentes',28,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (29,'es', NOW(), 1, 0, NOW(),'Log de auditoria',29,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (30,'es', NOW(), 1, 0, NOW(),'Material-concepto',30,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (31,'es', NOW(), 1, 0, NOW(),'Job de pruebas informadas y terceros',31,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (32,'es', NOW(), 1, 0, NOW(),'',32,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (33,'es', NOW(), 1, 0, NOW(),'',33,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (34,'es', NOW(), 1, 0, NOW(),'Peticiones por  cliente',34,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (35,'es', NOW(), 1, 0, NOW(),'Regla de facturación: Delegacion',35,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (36,'es', NOW(), 1, 0, NOW(),'Regla de facturación: Operación',36,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (37,'es', NOW(), 1, 0, NOW(),'Sector',37,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (38,'es', NOW(), 1, 0, NOW(),'Precios de la solicitud',38,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (39,'es', NOW(), 1, 0, NOW(),'Interlocutores de la solicitud',39,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (40,'es', NOW(), 1, 0, NOW(),'Contenedores',40,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (41,'es', NOW(), 1, 0, NOW(),'Textos de organización de ventas',41,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (42,'es', NOW(), 1, 0, NOW(),'Trazabilidad de las solicitudes',42,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (43,'es', NOW(), 1, 0, NOW(),'Resultado de la agrupación',43,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (44,'es', NOW(), 1, 0, NOW(),'Nombre del contrato capitativo',44,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (45,'es', NOW(), 1, 0, NOW(),'Facturación por fecha de petición',45,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (46,'es', NOW(), 1, 0, NOW(),'Facturas generadas',46,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (47,'es', NOW(), 1, 0, NOW(),'Materiales de pruebas incongruentes',47,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (48,'es', NOW(), 1, 0, NOW(),'Condiciones de precio',48,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (49,'es', NOW(), 1, 0, NOW(),'Sistemas Lims',49,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (50,'es', NOW(), 1, 0, NOW(),'Tipo de contrato',50,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (51,'es', NOW(), 1, 0, NOW(),'Precio especial',51,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (52,'es', NOW(), 1, 0, NOW(),'',52,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (53,'es', NOW(), 1, 0, NOW(),'Reglas de prefacturas',53,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (54,'es', NOW(), 1, 0, NOW(),'Regla de facturación: Prueba',54,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (55,'es', NOW(), 1, 0, NOW(),'Regla de facturación: Servicio Concertado',55,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (56,'es', NOW(), 1, 0, NOW(),'Sociedades',56,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (57,'es', NOW(), 1, 0, NOW(),'Materiales (Ventas)',57,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (58,'es', NOW(), 1, 0, NOW(),'Relacion sociedad centro y almacen',58,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (59,'es', NOW(), 1, 0, NOW(),'Textos de la solicitud',59,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (60,'es', NOW(), 1, 0, NOW(),'Precios de la solicitud',60,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (61,'es', NOW(), 1, 0, NOW(),'Fechas de la petición',61,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (62,'es', NOW(), 1, 0, NOW(),'Datos del paciente',62,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (63,'es', NOW(), 1, 0, NOW(),'Materiales de ventas',63,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (64,'es', NOW(), 1, 0, NOW(),'Textos de proveedores',64,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (65,'es', NOW(), 1, 0, NOW(),'',65,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (66,'es', NOW(), 1, 0, NOW(),'',66,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (67,'es', NOW(), 1, 0, NOW(),'Pruebas incongruentes',67,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (68,'es', NOW(), 1, 0, NOW(),'Datos adicionales',68,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (69,'es', NOW(), 1, 0, NOW(),'Determinación de oficina de ventas',69,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (70,'es', NOW(), 1, 0, NOW(),'Divisor de factura',70,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (71,'es', NOW(), 1, 0, NOW(),'',71,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (72,'es', NOW(), 1, 0, NOW(),'Periodos facturados',72,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (73,'es', NOW(), 1, 0, NOW(),'Estados',73,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (74,'es', NOW(), 1, 0, NOW(),'',74,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (75,'es', NOW(), 1, 0, NOW(),'Canal de distribución',75,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (76,'es', NOW(), 1, 0, NOW(),'Interlocutores de la solicitud',76,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (77,'es', NOW(), 1, 0, NOW(),'Textos de la posición',77,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (78,'es', NOW(), 1, 0, NOW(),'Datos clínicos',78,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (79,'es', NOW(), 1, 0, NOW(),'Codigos snomed',79,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (81,'es', NOW(), 1, 0, NOW(),'Datos del médico',81,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (82,'es', NOW(), 1, 0, NOW(),'Textos de materiales',82,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (83,'es', NOW(), 1, 0, NOW(),'Textos de paises',83,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (84,'es', NOW(), 1, 0, NOW(),'Trazabilidad de las pruebas',84,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (85,'es', NOW(), 1, 0, NOW(),'',85,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (86,'es', NOW(), 1, 0, NOW(),'Determinación de centro',86,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (87,'es', NOW(), 1, 0, NOW(),'Mensajes de error',87,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (88,'es', NOW(), 1, 0, NOW(),'Criterios de pruebas incongruentes',88,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (89,'es', NOW(), 1, 0, NOW(),'',89,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (90,'es', NOW(), 1, 0, NOW(),'Tipo de posición',90,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (91,'es', NOW(), 1, 0, NOW(),'',91,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (92,'es', NOW(), 1, 0, NOW(),'Reglas de facturación: Compañias',92,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (93,'es', NOW(), 1, 0, NOW(),'Reglas de facturación: Empresas',93,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (94,'es', NOW(), 1, 0, NOW(),'Reglas de facturación: Remitentes',94,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (95,'es', NOW(), 1, 0, NOW(),'Reglas de facturación: Sector',95,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (96,'es', NOW(), 1, 0, NOW(),'Reglas de facturación',96,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (97,'es', NOW(), 1, 0, NOW(),'Precio de las posiciones',97,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (98,'es', NOW(), 1, 0, NOW(),'Solicitud individual',98,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (99,'es', NOW(), 1, 0, NOW(),'Alertas',99,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (100,'es', NOW(), 1, 0, NOW(),'Alertas de las pruebas',100,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (101,'es', NOW(), 1, 0, NOW(),'',101,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (102,'es', NOW(), 1, 0, NOW(),'Textos de oficina de ventas',102,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (103,'es', NOW(), 1, 0, NOW(),'Transformación',103,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (104,'es', NOW(), 1, 0, NOW(),'Trazabilidad de documentos SAP',104,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (105,'es', NOW(), 1, 0, NOW(),'Mensajes',105,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (106,'es', NOW(), 1, 0, NOW(),'Estado del la solicitud',106,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (107,'es', NOW(), 1, 0, NOW(),'Datos adicionales',107,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (108,'es', NOW(), 1, 0, NOW(),'Determinación de organización de ventas',108,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (109,'es', NOW(), 1, 0, NOW(),'Nombre de entidades',109,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (110,'es', NOW(), 1, 0, NOW(),'Gestión del cambio',110,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (111,'es', NOW(), 1, 0, NOW(),'Alertas',111,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (112,'es', NOW(), 1, 0, NOW(),'Motivos de estados',112,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (113,'es', NOW(), 1, 0, NOW(),'Relación entre material y concepto de facturación',113,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (114,'es', NOW(), 1, 0, NOW(),'',114,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (115,'es', NOW(), 1, 0, NOW(),'',115,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (116,'es', NOW(), 1, 0, NOW(),'',116,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (117,'es', NOW(), 1, 0, NOW(),'Regla facturación: DelEmisora',117,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (118,'es', NOW(), 1, 0, NOW(),'Regla facturación: OrgVenta',118,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (119,'es', NOW(), 1, 0, NOW(),'Regla facturación: Referencia',119,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (120,'es', NOW(), 1, 0, NOW(),'Regla facturación: TipoPeticion',120,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (121,'es', NOW(), 1, 0, NOW(),'Cuentas de mayor de S4',121,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (122,'es', NOW(), 1, 0, NOW(),'Organización de ventas',122,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (123,'es', NOW(), 1, 0, NOW(),'Posiciones de la solicitud',123,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (124,'es', NOW(), 1, 0, NOW(),'Precio de las posiciones',124,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (125,'es', NOW(), 1, 0, NOW(),'Pruebas',125,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (126,'es', NOW(), 1, 0, NOW(),'Precio de las pruebas',126,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (127,'es', NOW(), 1, 0, NOW(),'Estado de la solicitud recibida',127,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (128,'es', NOW(), 1, 0, NOW(),'Textos de centros',128,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (129,'es', NOW(), 1, 0, NOW(),'Textos de divisas',129,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (130,'es', NOW(), 1, 0, NOW(),'Estados de la solicitud',130,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (131,'es', NOW(), 1, 0, NOW(),'Remitentes',131,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (132,'es', NOW(), 1, 0, NOW(),'Textos de tarifas',132,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (133,'es', NOW(), 1, 0, NOW(),'Tipos de posiciones',133,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (134,'es', NOW(), 1, 0, NOW(),'Reglas de las transformación',134,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (135,'es', NOW(), 1, 0, NOW(),'Trazabilidad de la solicitud agrupada',135,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (136,'es', NOW(), 1, 0, NOW(),'Parametros de facturación',136,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (137,'es', NOW(), 1, 0, NOW(),'Interlocutores del contrato',137,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (138,'es', NOW(), 1, 0, NOW(),'Determinación de sociedad',138,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (139,'es', NOW(), 1, 0, NOW(),'Condiciones de pruebas incongruentes',139,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (140,'es', NOW(), 1, 0, NOW(),'Motivos de rectificación',140,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (141,'es', NOW(), 1, 0, NOW(),'Tipo de petición',141,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (142,'es', NOW(), 1, 0, NOW(),'',142,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (143,'es', NOW(), 1, 0, NOW(),'',143,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (144,'es', NOW(), 1, 0, NOW(),'Regla de facturación: Cliente',144,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (145,'es', NOW(), 1, 0, NOW(),'Regla de facturación: Documento Unico',145,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (146,'es', NOW(), 1, 0, NOW(),'Regla de facturación: Polizas',146,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (147,'es', NOW(), 1, 0, NOW(),'Regla de facturación: Remitentes',147,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (148,'es', NOW(), 1, 0, NOW(),'Regla de facturación: Unidad productiva',148,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (149,'es', NOW(), 1, 0, NOW(),'Clientes',149,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (150,'es', NOW(), 1, 0, NOW(),'Oficina de ventas',150,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (151,'es', NOW(), 1, 0, NOW(),'Interlocutores de la posición',151,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (152,'es', NOW(), 1, 0, NOW(),'Solicitudes agrupadas',152,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (153,'es', NOW(), 1, 0, NOW(),'Peticiones',153,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (154,'es', NOW(), 1, 0, NOW(),'Estados de las pruebas',154,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (155,'es', NOW(), 1, 0, NOW(),'Solicitud recibida',155,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (156,'es', NOW(), 1, 0, NOW(),'Textos de centros de coste',156,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (157,'es', NOW(), 1, 0, NOW(),'Conceptos de facturación',157,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (158,'es', NOW(), 1, 0, NOW(),'Estados de facturación',158,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (159,'es', NOW(), 1, 0, NOW(),'Textos de interlocutores',159,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (160,'es', NOW(), 1, 0, NOW(),'Textos de regiones',160,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (161,'es', NOW(), 1, 0, NOW(),'Textos de sociedades',161,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (162,'es', NOW(), 1, 0, NOW(),'Textos de tipos de petición',162,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (163,'es', NOW(), 1, 0, NOW(),'Criterios de la transformación',163,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (164,'es', NOW(), 1, 0, NOW(),'Estados de las pruebas',164,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (165,'es', NOW(), 1, 0, NOW(),'Determinación de sector',165,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (166,'es', NOW(), 1, 0, NOW(),'Grupos de sectores',166,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (167,'es', NOW(), 1, 0, NOW(),'Historial de versiones',167,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (168,'es', NOW(), 1, 0, NOW(),'Datos modificados',168,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (169,'es', NOW(), 1, 0, NOW(),'',169,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (170,'es', NOW(), 1, 0, NOW(),'',170,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (171,'es', NOW(), 1, 0, NOW(),'Estados del proceso',171,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (172,'es', NOW(), 1, 0, NOW(),'Transiciones de estados',172,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (173,'es', NOW(), 1, 0, NOW(),'Parametros globales de cliente',173,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (174,'es', NOW(), 1, 0, NOW(),'',174,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (175,'es', NOW(), 1, 0, NOW(),'Materiales',175,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (176,'es', NOW(), 1, 0, NOW(),'Texto de organización de ventas',176,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (177,'es', NOW(), 1, 0, NOW(),'Textos de la posición',177,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (178,'es', NOW(), 1, 0, NOW(),'Posiciones de la solicitud',178,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (179,'es', NOW(), 1, 0, NOW(),'Estados de la petición',179,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (180,'es', NOW(), 1, 0, NOW(),'Datos de la operación',180,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (181,'es', NOW(), 1, 0, NOW(),'Textos de almacenes',181,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (182,'es', NOW(), 1, 0, NOW(),'Textos de clientes',182,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (183,'es', NOW(), 1, 0, NOW(),'Empresas',183,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (184,'es', NOW(), 1, 0, NOW(),'Textos de funcion de interlocutor',184,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (185,'es', NOW(), 1, 0, NOW(),'Textos de sector de ventas',185,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (186,'es', NOW(), 1, 0, NOW(),'Textos de tipos de contratos',186,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (187,'es', NOW(), 1, 0, NOW(),'Textos de unidades productivas',187,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (188,'es', NOW(), 1, 0, NOW(),'Trazabilidad al nivel de Albaren',188,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (189,'es', NOW(), 1, 0, NOW(),'Cargos de descuentos',189,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (190,'es', NOW(), 1, 0, NOW(),'',190,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (191,'es', NOW(), 1, 0, NOW(),'',191,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (192,'es', NOW(), 1, 0, NOW(),'',192,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (193,'es', NOW(), 1, 0, NOW(),'Estados secundarios',193,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (194,'es', NOW(), 1, 0, NOW(),'',194,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (195,'es', NOW(), 1, 0, NOW(),'',195,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (196,'es', NOW(), 1, 0, NOW(),'',196,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (197,'es', NOW(), 1, 0, NOW(),'',197,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (198,'es', NOW(), 1, 0, NOW(),'',198,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (199,'es', NOW(), 1, 0, NOW(),'',199,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (200,'es', NOW(), 1, 0, NOW(),'Ultimo estado secundario',200,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (201,'es', NOW(), 1, 0, NOW(),'',201,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (202,'es', NOW(), 1, 0, NOW(),'Actividad por cliente',202,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (203,'es', NOW(), 1, 0, NOW(),'Cabeceras de acto médico',203,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (204,'es', NOW(), 1, 0, NOW(),'Detalle de acto médico',204,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (205,'es', NOW(), 1, 0, NOW(),'Divisor de factura',205,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (206,'es', NOW(), 1, 0, NOW(),'Cabeceras de contratos',206,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (207,'es', NOW(), 1, 0, NOW(),'Cabeceras de capitativo fijo',207,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (208,'es', NOW(), 1, 0, NOW(),'Detalle de capitativo fijo',208,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (209,'es', NOW(), 1, 0, NOW(),'Cabeceras de capitativo variable',209,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (210,'es', NOW(), 1, 0, NOW(),'Detalle de capitativo variable',210,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (211,'es', NOW(), 1, 0, NOW(),'Cabeceras de fijo por petición',211,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (212,'es', NOW(), 1, 0, NOW(),'Detalle de fijo por petición',212,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (213,'es', NOW(), 1, 0, NOW(),'Cantidades por clave',213,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (214,'es', NOW(), 1, 0, NOW(),'Cantidades por contratos',214,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (215,'es', NOW(), 1, 0, NOW(),'Cantidades por estado',215,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (216,'es', NOW(), 1, 0, NOW(),'Clientes',216,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (217,'es', NOW(), 1, 0, NOW(),'Compañias',217,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (218,'es', NOW(), 1, 0, NOW(),'Contratos por clientes',218,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (219,'es', NOW(), 1, 0, NOW(),'Empresas',219,'Generic','Generic');
#¡REF!
#¡REF!
INSERT INTO IT_EntityListNameText VALUES (222,'es', NOW(), 1, 0, NOW(),'Estructura organizativa por cliente',222,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (223,'es', NOW(), 1, 0, NOW(),'Pruebas incongruentes por clientes',223,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (224,'es', NOW(), 1, 0, NOW(),'Interlocutores por clientes',224,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (225,'es', NOW(), 1, 0, NOW(),'Pacientes',225,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (226,'es', NOW(), 1, 0, NOW(),'Profesionales',226,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (227,'es', NOW(), 1, 0, NOW(),'Reglas de facturación por clientes',227,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (228,'es', NOW(), 1, 0, NOW(),'Reglas de pre-facturación por clientes',228,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (229,'es', NOW(), 1, 0, NOW(),'Remitentes',229,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (230,'es', NOW(), 1, 0, NOW(),'Visitadores',230,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (231,'es', NOW(), 1, 0, NOW(),'Grupo de estados (Prueba)',231,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (232,'es', NOW(), 1, 0, NOW(),'Grupo de estados (Solicitud)',232,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (233,'es', NOW(), 1, 0, NOW(),'Facturacion por clientes',233,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (234,'es', NOW(), 1, 0, NOW(),'Importes por clave',234,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (235,'es', NOW(), 1, 0, NOW(),'Importes por contratos',235,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (236,'es', NOW(), 1, 0, NOW(),'Importes por estados',236,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (237,'es', NOW(), 1, 0, NOW(),'Pruebas incongruentes',237,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (238,'es', NOW(), 1, 0, NOW(),'Prefactura de capitativo variable',238,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (239,'es', NOW(), 1, 0, NOW(),'Prefactura Capitativo Variable Cabecera',239,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (240,'es', NOW(), 1, 0, NOW(),'',240,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (241,'es', NOW(), 1, 0, NOW(),'',241,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (242,'es', NOW(), 1, 0, NOW(),'',242,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (243,'es', NOW(), 1, 0, NOW(),'',243,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (244,'es', NOW(), 1, 0, NOW(),'Presupuestos',244,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (245,'es', NOW(), 1, 0, NOW(),'Condiciones de precio',245,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (246,'es', NOW(), 1, 0, NOW(),'Pruebas',246,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (247,'es', NOW(), 1, 0, NOW(),'Actividad',247,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (248,'es', NOW(), 1, 0, NOW(),'Actividad por cliente',248,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (249,'es', NOW(), 1, 0, NOW(),'Resumen actividad por contratos',249,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (250,'es', NOW(), 1, 0, NOW(),'Actividad',250,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (251,'es', NOW(), 1, 0, NOW(),'Actividad por contratos',251,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (252,'es', NOW(), 1, 0, NOW(),'Alertas',252,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (253,'es', NOW(), 1, 0, NOW(),'Alertas a nivel de prueba',253,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (254,'es', NOW(), 1, 0, NOW(),'Clasificación',254,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (255,'es', NOW(), 1, 0, NOW(),'Condiciones de precio',255,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (256,'es', NOW(), 1, 0, NOW(),'Contrato relacionado',256,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (257,'es', NOW(), 1, 0, NOW(),'',257,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (258,'es', NOW(), 1, 0, NOW(),'Datos del perfil',258,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (259,'es', NOW(), 1, 0, NOW(),'Datos de la solicitud',259,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (260,'es', NOW(), 1, 0, NOW(),'Estados de la solicitud',260,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (261,'es', NOW(), 1, 0, NOW(),'Estados de la solicitud',261,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (262,'es', NOW(), 1, 0, NOW(),'Flujo del proceso',262,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (263,'es', NOW(), 1, 0, NOW(),'',263,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (264,'es', NOW(), 1, 0, NOW(),'',264,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (265,'es', NOW(), 1, 0, NOW(),'',265,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (266,'es', NOW(), 1, 0, NOW(),'',266,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (267,'es', NOW(), 1, 0, NOW(),'Interlocutores de la solicitud',267,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (268,'es', NOW(), 1, 0, NOW(),'Mensajes generados',268,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (269,'es', NOW(), 1, 0, NOW(),'Motivos de rechazo',269,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (270,'es', NOW(), 1, 0, NOW(),'Motivo de estados',270,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (271,'es', NOW(), 1, 0, NOW(),'Datos del perfil',271,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (272,'es', NOW(), 1, 0, NOW(),'Datos de la prueba',272,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (273,'es', NOW(), 1, 0, NOW(),'Datos de la solicitud',273,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (274,'es', NOW(), 1, 0, NOW(),'Ultimo estado de la prueba',274,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (275,'es', NOW(), 1, 0, NOW(),'Ultimo estado de la solicitud',275,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (276,'es', NOW(), 1, 0, NOW(),'Mensajes',276,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (277,'es', NOW(), 1, 0, NOW(),'Detalle del flujo',277,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (278,'es', NOW(), 1, 0, NOW(),'Flujo de solicitudes',278,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (279,'es', NOW(), 1, 0, NOW(),'',279,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (280,'es', NOW(), 1, 0, NOW(),'',280,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (281,'es', NOW(), 1, 0, NOW(),'',281,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (282,'es', NOW(), 1, 0, NOW(),'',282,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (283,'es', NOW(), 1, 0, NOW(),'',283,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (284,'es', NOW(), 1, 0, NOW(),'',284,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (285,'es', NOW(), 1, 0, NOW(),'',285,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (286,'es', NOW(), 1, 0, NOW(),'',286,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (287,'es', NOW(), 1, 0, NOW(),'Actividad de pool de facturación',287,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (288,'es', NOW(), 1, 0, NOW(),'Pruebas informadas',288,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (289,'es', NOW(), 1, 0, NOW(),'Pruebas de terceros',289,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (290,'es', NOW(), 1, 0, NOW(),'Proveedor de pruebas informadas',290,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (291,'es', NOW(), 1, 0, NOW(),'Proveedor de pruebas de terceros',291,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (292,'es', NOW(), 1, 0, NOW(),'',292,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (293,'es', NOW(), 1, 0, NOW(),'',293,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (294,'es', NOW(), 1, 0, NOW(),'',294,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (295,'es', NOW(), 1, 0, NOW(),'',295,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (296,'es', NOW(), 1, 0, NOW(),'Datos del interlocutor recibido',296,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (297,'es', NOW(), 1, 0, NOW(),'Interlocutores',297,'Generic','Generic');
INSERT INTO IT_EntityListNameText VALUES (298,'es', NOW(), 1, 0, NOW(),'Interlocutores recibidos',298,'Generic','Generic');
