INSERT INTO T_MasDataEstado VALUES(1,1,0,'SE',1,'Peticion sin estados', NOW(),1,1,0, NOW(),'Sin estado',1,'Generic','Generic',1);
INSERT INTO T_MasDataEstado VALUES(2,1,0,'CR',1,'La petición ha sido creada en el sistema origen y ha llegado a SCP.', NOW(),1,0,0, NOW(),'No facturable',1,'Generic','Generic',1);
INSERT INTO T_MasDataEstado VALUES(3,1,0,'VA',2,'Todas las pruebas de la petición han sido validadas.', NOW(),1,1,0, NOW(),'Validada / Autorizada',1,'Generic','Generic',1);
INSERT INTO T_MasDataEstado VALUES(4,1,1,'FB',3,'La petición cumple con todos los requisitos de facturación. Aplica cuando el cliente factura por fecha de petición o cuando todas las pruebas de una petición han sido validadas.', NOW(),1,0,0, NOW(),'Facturable',1,'Generic','Generic',2);
INSERT INTO T_MasDataEstado VALUES(5,1,1,'EX',0,'La petición contiene pruebas Incongruentes o no facturables indicado vía sistema integrador', NOW(),1,0,0, NOW(),'Excluida',1,'Generic','Generic',3);
INSERT INTO T_MasDataEstado VALUES(6,1,0,'FN',2,'La petición está en proceso de facturación.', NOW(),1,1,0, NOW(),'Facturando',1,'Generic','Generic',1);
INSERT INTO T_MasDataEstado VALUES(7,1,1,'PC',2,'Pedido Creado', NOW(),1,0,0, NOW(),'Pedido creado',1,'Generic','Generic',4);
INSERT INTO T_MasDataEstado VALUES(8,1,1,'F',3,'Todas las pruebas de la petición han sido facturadas.', NOW(),1,0,0, NOW(),'Facturada',1,'Generic','Generic',4);
INSERT INTO T_MasDataEstado VALUES(9,1,1,'PF',2,'La prueba o petición ha sido pre-facturada', NOW(),1,0,0, NOW(),'Parcialmente procesada',1,'Generic','Generic',4);
INSERT INTO T_MasDataEstado VALUES(10,1,1,'PA',2,'Pedido Abono', NOW(),1,0,0, NOW(),'Pedido abono',1,'Generic','Generic',4);
INSERT INTO T_MasDataEstado VALUES(11,1,1,'R',2,'La petición ha sido rectificada.', NOW(),1,0,0, NOW(),'Rectificada',1,'Generic','Generic',2);
INSERT INTO T_MasDataEstado VALUES(12,1,1,'BLK',1,'Petición/Prueba bloqueada', NOW(),1,0,0, NOW(),'Bloqueada',1,'Generic','Generic',1);
INSERT INTO T_MasDataEstado VALUES(13,1,1,'ERR',1,'Prueba Errónea', NOW(),1,0,0, NOW(),'Errónea',1,'Generic','Generic',1);
INSERT INTO T_MasDataEstado VALUES(14,1,1,'CO',3,'Cobrada', NOW(),1,0,0, NOW(),'Cobrada',2,'Generic','Generic',4);
INSERT INTO T_MasDataEstado VALUES(15,1,1,'PCO',2,'Parcialmente cobrada', NOW(),1,0,0, NOW(),'Parcialmente cobrada',2,'Generic','Generic',4);
INSERT INTO T_MasDataEstado VALUES(16,1,1,'LIQ',3,'Liquidada', NOW(),1,0,0, NOW(),'Liquidada',2,'Generic','Generic',4);
INSERT INTO T_MasDataEstado VALUES(17,1,1,'AB',3,'Abonada', NOW(),1,0,0, NOW(),'Abonada',2,'Generic','Generic',4);
INSERT INTO T_MasDataEstado VALUES(18,1,1,'DEL',1,'La petición ha sido borrada', NOW(),1,0,0, NOW(),'Borrada',1,'Generic','Generic',1);
INSERT INTO T_MasDataEstado VALUES(19,1,1,'PP',2,'Algunas pruebas de la petición han sido procesadas en procesos de facturación.', NOW(),1,0,0, NOW(),'Parcialmente procesada',1,'Generic','Generic',4);
