package com.echevarne.sap.cloud.facturacion.constants;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class ConstEntities {
	
	/**
	 * Schemas
	 * 
	 */
	public static final String SCHEMA_SLT_REPLICATION = "SLT_REPLICATION";
	public static final String SCHEMA_FACTURACION = "FACTURACION";
	
	/**
	 * Prefijos y configuraciones
	 */
	public static final String ENTIDAD_REPLICA = "S4";
	public static final String ENTIDAD_TABLA = "T_";
	public static final String ENTIDAD_VISTA = "V_";
	public static final String ENTIDAD_TABLA_INTERNA = "IT_";

	public static final String ENTIDAD_TIPO_MASTER_DATA = "MasData";
	public static final String ENTIDAD_TIPO_ENTIDADES = "Entity";
	public static final String ENTIDAD_TIPO_CONVERSIONES = "Conversion";
	public static final String ENTIDAD_TIPO_INCONGRUENTES = "Incong";
	public static final String ENTIDAD_TIPO_SOLICITUD_MUESTREO = "SolMues";
	public static final String ENTIDAD_TIPO_PETICION_MUESTREO = "PetMues";
	public static final String ENTIDAD_TIPO_PETICION_MUESTREO_ITEM = "PetMuesItem";
	public static final String ENTIDAD_TIPO_REGLAS_DE_FACTURACION = "RegFact";
	public static final String ENTIDAD_TIPO_SOLICITUD_INDIVIDUAL = "SolInd";
	public static final String ENTIDAD_TIPO_SOLICITUD_INDIVIDUAL_ITEM = "SolIndItem";
	public static final String ENTIDAD_TIPO_SOLICITUD_AGRUPADA = "SolAgr";
	public static final String ENTIDAD_TIPO_SOLICITUD_AGRUPADA_ITEM = "SolAgrItem";
	public static final String ENTIDAD_TIPO_TRAZABILIDAD = "Trazabilidad";
	public static final String ENTIDAD_TIPO_TRAZABILIDAD_SOLICITUD = "TrazabilidadSolicitud";
	public static final String ENTIDAD_TIPO_TRANSFORMACION = "Transformacion";
	public static final String ENTIDAD_TIPO_GENERICO = "";
	public static final String ENTIDAD_TIPO_MENSAJES = "Messages";
	public static final String ENTIDAD_TIPO_LOG_DE_FACTURACION = "FactLog";
	public static final String ENTIDAD_TIPO_CONTRATO_CAPITATIVO = "ContratoCapitativo";
	public static final String ENTIDAD_TIPO_GESTIÓN_DE_CAMBIOS = "GestionCambio";
	
	/**
	 * 
	 * Entidades
	 * 
	 */
	
	/*
	 * Replica de datos
	 * 
	 */
	public static final String ENTIDAD_COMPANIES = ENTIDAD_REPLICA + ENTIDAD_TIPO_GENERICO + "COMPANIES";
	public static final String ENTIDAD_CUSTOMERS = ENTIDAD_REPLICA + ENTIDAD_TIPO_GENERICO + "CUSTOMERS";
	public static final String ENTIDAD_DISTRIBUTIONCHANNELTEXT = ENTIDAD_REPLICA + ENTIDAD_TIPO_GENERICO + "DISTRIBUTIONCHANNELTEXT";
	public static final String ENTIDAD_DIVISIONTEXT = ENTIDAD_REPLICA + ENTIDAD_TIPO_GENERICO + "DIVISIONTEXT";
	public static final String ENTIDAD_MATERIALS = ENTIDAD_REPLICA + ENTIDAD_TIPO_GENERICO + "MATERIALS";
	public static final String ENTIDAD_MATERIALSALES = ENTIDAD_REPLICA + ENTIDAD_TIPO_GENERICO + "MATERIALSALES";
	public static final String ENTIDAD_SALESOFFICETEXT = ENTIDAD_REPLICA + ENTIDAD_TIPO_GENERICO + "SALESOFFICETEXT";
	public static final String ENTIDAD_SALESORGANIZATION = ENTIDAD_REPLICA + ENTIDAD_TIPO_GENERICO + "SALESORGANIZATION";
	public static final String ENTIDAD_SALESORGANIZATIONTEXT = ENTIDAD_REPLICA + ENTIDAD_TIPO_GENERICO + "SALESORGANIZATIONTEXT";
	public static final String ENTIDAD_ZOTC_SD_DET_CUEN = ENTIDAD_REPLICA + ENTIDAD_TIPO_GENERICO + "ZOTC_SD_DET_CUEN";
	
	/*
	 * Tablas internas
	 * 
	 */
	public static final String ENTIDAD_ENTITYFIELDNAMETEXT = ENTIDAD_TABLA_INTERNA + ENTIDAD_TIPO_ENTIDADES + "FieldNameText";
	public static final String ENTIDAD_ENTITYFIELDSNAME = ENTIDAD_TABLA_INTERNA + ENTIDAD_TIPO_ENTIDADES + "FieldsName";
	public static final String ENTIDAD_ENTITYLISTNAME = ENTIDAD_TABLA_INTERNA + ENTIDAD_TIPO_ENTIDADES + "ListName";
	public static final String ENTIDAD_ENTITYLISTNAMETEXT = ENTIDAD_TABLA_INTERNA + ENTIDAD_TIPO_ENTIDADES + "ListNameText";
	public static final String ENTIDAD_INCONGINCONG_SEC = ENTIDAD_TABLA_INTERNA + ENTIDAD_TIPO_INCONGRUENTES + "Incong_Sec";
	
	/*
	 * Tablas
	 * 
	 */
	public static final String ENTIDAD_AGRPARAMETROSFACTURACION = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "AgrParametrosFacturacion";
	public static final String ENTIDAD_AGRRESULTADO = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "AgrResultado";
	public static final String ENTIDAD_BLOQUEOCORTESIA = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "BloqueoCortesia";
	public static final String ENTIDAD_CARGODESCUENTO = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "CargoDescuento";
	public static final String ENTIDAD_CONDICIONPRECIOADICIONALITEM = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "CondicionPrecioAdicionalItem";
	public static final String ENTIDAD_CONDICIONPRECIOADICIONALSOLICITUD = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "CondicionPrecioAdicionalSolicitud";
	public static final String ENTIDAD_REGFACTCONFIGURACIONDIVISORFACTURA = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "ConfiguracionDivisorFactura";
	public static final String ENTIDAD_REGFACTINCLUSION = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "Inclusion";
	public static final String ENTIDAD_CONTRATOCAPITATIVOINTERLOCUTORES = ENTIDAD_TABLA + ENTIDAD_TIPO_CONTRATO_CAPITATIVO + "Interlocutores";
	public static final String ENTIDAD_CONTRATOCAPITATIVOOFICINAVENTA = ENTIDAD_TABLA + ENTIDAD_TIPO_CONTRATO_CAPITATIVO + "OficinaVenta";
	public static final String ENTIDAD_CONTRATOCAPITATIVOPROVREMITENTE = ENTIDAD_TABLA + ENTIDAD_TIPO_CONTRATO_CAPITATIVO + "ProvRemitente";
	public static final String ENTIDAD_CONTRATOCAPITATIVOPOLIZAS = ENTIDAD_TABLA + ENTIDAD_TIPO_CONTRATO_CAPITATIVO + "Polizas";
	public static final String ENTIDAD_CONTRATOCAPITATIVO = ENTIDAD_TABLA + ENTIDAD_TIPO_CONTRATO_CAPITATIVO + "";
	public static final String ENTIDAD_CONTRATOCAPITATIVOTEXT = ENTIDAD_TABLA + ENTIDAD_TIPO_CONTRATO_CAPITATIVO + "Text";
	public static final String ENTIDAD_CONVERSIONCENTRO = ENTIDAD_TABLA + ENTIDAD_TIPO_CONVERSIONES + "Centro";
	public static final String ENTIDAD_CONVERSIONOFICINAVENTAS = ENTIDAD_TABLA + ENTIDAD_TIPO_CONVERSIONES + "OficinaVentas";
	public static final String ENTIDAD_CONVERSIONORGANIZACIONVENTAS = ENTIDAD_TABLA + ENTIDAD_TIPO_CONVERSIONES + "OrganizacionVentas";
	public static final String ENTIDAD_CONVERSIONSECTOR = ENTIDAD_TABLA + ENTIDAD_TIPO_CONVERSIONES + "Sector";
	public static final String ENTIDAD_CONVERSIONSOCIEDAD = ENTIDAD_TABLA + ENTIDAD_TIPO_CONVERSIONES + "Sociedad";
	public static final String ENTIDAD_DATOSPAGADOR = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "DatosPagador";
	public static final String ENTIDAD_ENTITYVERSIONHISTORY = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "EntityVersionHistory";
	public static final String ENTIDAD_ERRORMESSAGES = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "ErrorMessages";
	public static final String ENTIDAD_FACTURABLEFECHAPETICION = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "FacturableFechaPeticion";
	public static final String ENTIDAD_FACTLOGGENERADAS = ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "Generadas";
	public static final String ENTIDAD_FACTLOGCONTROL = ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "Control";
	public static final String ENTIDAD_FACTLOGCONTROLTIPOLOGIA = ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "ControlTipologia";
	public static final String ENTIDAD_FACTLOGPROCESO = ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "Proceso";
	
	public static final String ENTIDAD_FACTLOGPERIODOS = ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "Periodos";
	public static final String ENTIDAD_FACTLOGPERIODOSCLIENTES = ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "PeriodosClientes";
	public static final String ENTIDAD_FACTLOGPERIODOSORGVENTAS = ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "PeriodosOrgVentas";
	public static final String ENTIDAD_FACTLOGPERIODOSTIPOLOGIAS = ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "PeriodosTipologias";
	public static final String ENTIDAD_FACTLOGPERIODOSTIPOLOGIASCLAVES = ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "PeriodosTipologiasClaves";
	public static final String ENTIDAD_FACTLOGPERIODOSCODDELEGACION = ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "PeriodosCodDelegacion";
	public static final String ENTIDAD_FACTLOGPERIODOSREMITENTES = ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "PeriodosRemitentes";
	public static final String ENTIDAD_FACTLOGPERIODOSCIAS = ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "PeriodosCias";
	public static final String ENTIDAD_FACTLOGPERIODOSTIPOSPETICION= ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "PeriodosTiposPeticion";
	public static final String ENTIDAD_FACTLOGPERIODOSPRUEBAS= ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "PeriodosPruebas";
	public static final String ENTIDAD_FACTLOGPERIODOSSECTORES= ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "PeriodosSectores";
	public static final String ENTIDAD_FACTLOGPERIODOSCODPETICION= ENTIDAD_TABLA + ENTIDAD_TIPO_LOG_DE_FACTURACION + "PeriodosCodPeticion";
	
	public static final String ENTIDAD_GESTIONCAMBIO = ENTIDAD_TABLA + ENTIDAD_TIPO_GESTIÓN_DE_CAMBIOS + "0";
	public static final String ENTIDAD_GESTIONCAMBIODATA = ENTIDAD_TABLA + ENTIDAD_TIPO_GESTIÓN_DE_CAMBIOS + "Data";
	public static final String ENTIDAD_GRUPOSSECTORES = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "GruposSectores";
	public static final String ENTIDAD_INCONGINCONG_COND = ENTIDAD_TABLA + ENTIDAD_TIPO_INCONGRUENTES + "Incong_Cond";
	public static final String ENTIDAD_INCONGINCONG_CRIT = ENTIDAD_TABLA + ENTIDAD_TIPO_INCONGRUENTES + "Incong_Crit";
	public static final String ENTIDAD_INCONGINCONG_MAT = ENTIDAD_TABLA + ENTIDAD_TIPO_INCONGRUENTES + "Incong_Mat";
	public static final String ENTIDAD_LOG = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "Log";
	public static final String ENTIDAD_MASDATAALERTA = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "Alerta";
	public static final String ENTIDAD_MASDATAALERTAPRIVADOS = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "AlertaPrivados";
	public static final String ENTIDAD_MASDATAALERTA_ALERTAPRIVADOS = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "Alerta_AlertaPrivados";
	public static final String ENTIDAD_MASDATACONDITIONPRICE = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "ConditionPrice";
	public static final String ENTIDAD_MASDATADESCUENTO = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "Descuento";
	public static final String ENTIDAD_MASDATAESTADO = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "Estado";
	public static final String ENTIDAD_MASDATACOMBINACIONESTADO = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "CombinacionEstado";
	public static final String ENTIDAD_MASDATAESTADOSGRUPO = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "EstadosGrupo";
	public static final String ENTIDAD_MASDATAMETODOPAGO = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "MetodoPago";
	public static final String ENTIDAD_MASDATAMOTIVOSESTADO = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "MotivosEstado";
	public static final String ENTIDAD_MASDATAMOTIVOSRECTIFICACION = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "MotivosRectificacion";
	public static final String ENTIDAD_MASDATAPROCESSCONTROLSTATUS = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "ProcessControlStatus";
	public static final String ENTIDAD_MASDATASISTEMASLIMS = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "SistemasLims";
	public static final String ENTIDAD_MASDATATIPOCONTRATO = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "TipoContrato";
	public static final String ENTIDAD_MASDATATIPOPETICION = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "TipoPeticion";
	public static final String ENTIDAD_MASDATATIPOPOSICION = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "TipoPosicion";
	public static final String ENTIDAD_MASDATATIPOLOGIAFACTURACION = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "TipologiaFacturacion";
	public static final String ENTIDAD_MASDATATRANSICIONESTADO = ENTIDAD_TABLA + ENTIDAD_TIPO_MASTER_DATA + "TransicionEstado";
	public static final String ENTIDAD_MATCONCEPTOFACT = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "MatConceptoFact";
	public static final String ENTIDAD_MESSAGES = ENTIDAD_TABLA + ENTIDAD_TIPO_MENSAJES + "0";
	public static final String ENTIDAD_PARAMETROSGENERALES = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "ParametrosGenerales";
	public static final String ENTIDAD_PETMUESALERTA = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO + "Alerta";
	public static final String ENTIDAD_PETMUESCLINICOS = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO + "Clinicos";
	public static final String ENTIDAD_PETMUESCONTENEDOR = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO + "Contenedor";
	public static final String ENTIDAD_PETMUESESTADO = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO + "Estado";
	public static final String ENTIDAD_PETMUESFECHAS = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO + "Fechas";
	public static final String ENTIDAD_PETMUESINTERLOCUTORES = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO + "Interlocutores";
	public static final String ENTIDAD_PETMUESITEMALERTA = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO_ITEM + "Alerta";
	public static final String ENTIDAD_PETMUESITEMESTADO = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO_ITEM + "Estado";
	public static final String ENTIDAD_PETMUESITEMPRECIO = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO_ITEM + "Precio";
	public static final String ENTIDAD_PETMUESITEMSNOMED = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO_ITEM + "Snomed";
	public static final String ENTIDAD_PETMUESMEDICO = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO + "Medico";
	public static final String ENTIDAD_PETMUESOPERACION = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO + "Operacion";
	public static final String ENTIDAD_PETMUESPACIENTE = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO + "Paciente";
	public static final String ENTIDAD_PETMUESPRECIO = ENTIDAD_TABLA + ENTIDAD_TIPO_PETICION_MUESTREO + "Precio";
	public static final String ENTIDAD_PETICIONMUESTREO = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "PeticionMuestreo";
	public static final String ENTIDAD_PETICIONMUESTREOITEMS = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "PeticionMuestreoItems";
	public static final String ENTIDAD_PRECIOESPECIAL = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "PrecioEspecial";
	public static final String ENTIDAD_PROVEEDORPRUEBAINFORMADA = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "ProveedorPruebaInformada";
	public static final String ENTIDAD_PROVEEDORPRUEBATERCEROS = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "ProveedorPruebaTerceros";
	public static final String ENTIDAD_REGFACTCLIENTE = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "Cliente";
	public static final String ENTIDAD_REGFACTCOMPANIAS = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "Companias";
	public static final String ENTIDAD_REGFACTDELEMISORA = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "DelEmisora";
	public static final String ENTIDAD_REGFACTDELEGACION = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "Delegacion";
	public static final String ENTIDAD_REGFACTDOCUMENTOUNICO = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "DocumentoUnico";
	public static final String ENTIDAD_REGFACTEMPRESAS = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "Empresas";
	public static final String ENTIDAD_REGFACTOPERACION = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "Operacion";
	public static final String ENTIDAD_REGFACTORGVENTA = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "OrgVenta";
	public static final String ENTIDAD_REGFACTPOLIZAS = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "Polizas";
	public static final String ENTIDAD_REGFACTPROVREMITENTE = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "ProvRemitente";
	public static final String ENTIDAD_REGFACTPRUEBA = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "Prueba";
	public static final String ENTIDAD_REGFACTREFERENCIA = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "Referencia";
	public static final String ENTIDAD_REGFACTREMITENTES = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "Remitentes";
	public static final String ENTIDAD_REGFACTSECTOR = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "Sector";
	public static final String ENTIDAD_REGFACTSERVICIOCONC = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "ServicioConc";
	public static final String ENTIDAD_REGFACTTIPOPETICION = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "TipoPeticion";
	public static final String ENTIDAD_REGFACTUNIDADPROD = ENTIDAD_TABLA + ENTIDAD_TIPO_REGLAS_DE_FACTURACION + "UnidadProd";
	public static final String ENTIDAD_REGLAFACTURAPORFECHA = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "ReglaFacturaPorFecha";
	public static final String ENTIDAD_REGLAFACTURACION = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "ReglaFacturacion";
	public static final String ENTIDAD_REGLAPREFACTURA = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "ReglaPrefactura";
	public static final String ENTIDAD_SOCIEDADCENTROALMACEN = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "SociedadCentroAlmacen";
	public static final String ENTIDAD_SOLAGRITEMPARTNER = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_AGRUPADA_ITEM + "Partner";
	public static final String ENTIDAD_SOLAGRITEMPRICING = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_AGRUPADA_ITEM + "Pricing";
	public static final String ENTIDAD_SOLAGRITEMTEXTS = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_AGRUPADA_ITEM + "Texts";
	public static final String ENTIDAD_SOLAGRITEMS = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_AGRUPADA_ITEM + "s";
	public static final String ENTIDAD_SOLAGRPARTNER = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_AGRUPADA + "Partner";
	public static final String ENTIDAD_SOLAGRPRICING = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_AGRUPADA + "Pricing";
	public static final String ENTIDAD_SOLAGRPRUEBAACTIVIDAD = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_AGRUPADA + "PruebaActividad";
	public static final String ENTIDAD_SOLAGRPRUEBAINFORMADA = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_AGRUPADA + "PruebaInformada";
	public static final String ENTIDAD_SOLAGRPRUEBAINFORMADAITEMS = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_AGRUPADA + "PruebaInformadaItems";
	public static final String ENTIDAD_SOLAGRPRUEBATERCEROS = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_AGRUPADA + "PruebaTerceros";
	public static final String ENTIDAD_SOLAGRPRUEBATERCEROSITEMS = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_AGRUPADA + "PruebaTercerosItems";
	public static final String ENTIDAD_SOLAGRTEXTS = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_AGRUPADA + "Texts";
	public static final String ENTIDAD_SOLINDITEMPARTNER = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_INDIVIDUAL_ITEM + "Partner";
	public static final String ENTIDAD_SOLINDITEMPRICING = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_INDIVIDUAL_ITEM + "Pricing";
	public static final String ENTIDAD_SOLINDITEMTEXTS = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_INDIVIDUAL_ITEM + "Texts";
	public static final String ENTIDAD_SOLINDITEMS = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_INDIVIDUAL_ITEM + "s";
	public static final String ENTIDAD_SOLINDPARTNER = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_INDIVIDUAL + "Partner";
	public static final String ENTIDAD_SOLINDPRICING = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_INDIVIDUAL + "Pricing";
	public static final String ENTIDAD_SOLINDTEXTS = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_INDIVIDUAL + "Texts";
	public static final String ENTIDAD_SOLMUESESTADO = ENTIDAD_TABLA + ENTIDAD_TIPO_SOLICITUD_MUESTREO + "Estado";
	public static final String ENTIDAD_SOLICITUDINDIVIDUAL = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "SolicitudIndividual";
	public static final String ENTIDAD_SOLICITUDMUESTREO = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "SolicitudMuestreo";
	public static final String ENTIDAD_SOLICITUDESAGRUPADAS = ENTIDAD_TABLA + ENTIDAD_TIPO_GENERICO + "SolicitudesAgrupadas";
	public static final String ENTIDAD_TRANSFORMACION = ENTIDAD_TABLA + ENTIDAD_TIPO_TRANSFORMACION + "0";
	public static final String ENTIDAD_TRANSFORMACIONCRITERIA = ENTIDAD_TABLA + ENTIDAD_TIPO_TRANSFORMACION + "Criteria";
	public static final String ENTIDAD_TRANSFORMACIONRULE = ENTIDAD_TABLA + ENTIDAD_TIPO_TRANSFORMACION + "Rule";
	public static final String ENTIDAD_TRAZABILIDAD = ENTIDAD_TABLA + ENTIDAD_TIPO_TRAZABILIDAD + "0";
	public static final String ENTIDAD_TRAZABILIDADCLASIFICACION = ENTIDAD_TABLA + ENTIDAD_TIPO_TRAZABILIDAD + "Clasificacion";
	public static final String ENTIDAD_TRAZABILIDADESTHISTORY = ENTIDAD_TABLA + ENTIDAD_TIPO_TRAZABILIDAD + "EstHistory";
	public static final String ENTIDAD_TRAZABILIDADSOLICITUDESTHISTORY = ENTIDAD_TABLA + ENTIDAD_TIPO_TRAZABILIDAD_SOLICITUD + "EstHistory";
	public static final String ENTIDAD_TRAZABILIDADSOLICITUD = ENTIDAD_TABLA + ENTIDAD_TIPO_TRAZABILIDAD_SOLICITUD + "0";
	public static final String ENTIDAD_TRAZABILIDADSOLICITUDAGR = ENTIDAD_TABLA + ENTIDAD_TIPO_TRAZABILIDAD_SOLICITUD + "Agr";
	public static final String ENTIDAD_TRAZABILIDADSOLICITUDDOCCONTABLE = ENTIDAD_TABLA + ENTIDAD_TIPO_TRAZABILIDAD_SOLICITUD + "DocContable";
	public static final String ENTIDAD_TRAZABILIDADSOLICITUDDOCCONTABLEITEM = ENTIDAD_TABLA + ENTIDAD_TIPO_TRAZABILIDAD_SOLICITUD + "DocContableItem";
	public static final String ENTIDAD_TRAZABILIDADSOLICITUDMESSAGES = ENTIDAD_TABLA + ENTIDAD_TIPO_TRAZABILIDAD_SOLICITUD + "Messages";
	public static final String ENTIDAD_TRAZABILIDADSOLICITUDPROCESSSTATUS = ENTIDAD_TABLA + ENTIDAD_TIPO_TRAZABILIDAD_SOLICITUD + "ProcessStatus";
	
	/*
	 * 
	 * Vistas
	 * 
	 */
	
	public static final String ENTIDAD_VCANAL_DISTRIBUCION = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VCANAL_DISTRIBUCION";
	public static final String ENTIDAD_VCECO = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VCECO";
	public static final String ENTIDAD_VCLIENTES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VCLIENTES";
	public static final String ENTIDAD_VCOMPANIAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VCOMPANIAS";
	public static final String ENTIDAD_VCONCEPTOS_FACT = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VCONCEPTOS_FACT";
	public static final String ENTIDAD_VDIVISAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VDIVISAS";
	public static final String ENTIDAD_VEMPRESAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VEMPRESAS";
	public static final String ENTIDAD_VESTADO_FACTU = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VESTADO_FACTU";
	public static final String ENTIDAD_VESTADO_TRAZA = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VESTADO_TRAZA";
	public static final String ENTIDAD_VFUNCION_INTER = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VFUNCION_INTER";
	public static final String ENTIDAD_VIMPUESTOS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VIMPUESTOS";
	public static final String ENTIDAD_VINTERLOCUTORES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VINTERLOCUTORES";
	public static final String ENTIDAD_VMATERIALES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VMATERIALES";
	public static final String ENTIDAD_VMATERIAL_VENTAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VMATERIAL_VENTAS";
	public static final String ENTIDAD_VOFICINA_VENTAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VOFICINA_VENTAS";
	public static final String ENTIDAD_VORGANIZACION_VENTAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VORGANIZACION_VENTAS";
	public static final String ENTIDAD_VPAISES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VPAISES";
	public static final String ENTIDAD_VPROVEEDORES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VPROVEEDORES";
	public static final String ENTIDAD_VREGIONES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VREGIONES";
	public static final String ENTIDAD_VREMITENTES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VREMITENTES";
	public static final String ENTIDAD_VSECTOR_VENTAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VSECTOR_VENTAS";
	public static final String ENTIDAD_VSISTEMAS_LIMS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VSISTEMAS_LIMS";
	public static final String ENTIDAD_VSOCIEDADES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VSOCIEDADES";
	public static final String ENTIDAD_VTARIFAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VTARIFAS";
	public static final String ENTIDAD_VTIPOLOGIAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VTIPOLOGIAS";
	public static final String ENTIDAD_VTIPO_CONTRATO = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VTIPO_CONTRATO";
	public static final String ENTIDAD_VTIPO_PETICION = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VTIPO_PETICION";
	public static final String ENTIDAD_VTIPO_POSICION = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VTIPO_POSICION";
	public static final String ENTIDAD_VUNIDADES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VUNIDADES";
	public static final String ENTIDAD_VUNIDADES_PRODUCTIVAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "VUNIDADES_PRODUCTIVAS";
	public static final String ENTIDAD_ACCAB_AM = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "ACCAB_AM";
	public static final String ENTIDAD_ACCAB_CF = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "ACCAB_CF";
	public static final String ENTIDAD_ACCAB_CV = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "ACCAB_CV";
	public static final String ENTIDAD_ACCAB_FP = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "ACCAB_FP";
	public static final String ENTIDAD_ACCLIENTES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "ACCLIENTES";
	public static final String ENTIDAD_ACDEAM = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "ACDEAM";
	public static final String ENTIDAD_ACDECF = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "ACDECF";
	public static final String ENTIDAD_ACDECV = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "ACDECV";
	public static final String ENTIDAD_ACDEFP = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "ACDEFP";
	public static final String ENTIDAD_ACDIAM = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "ACDIAM";
	public static final String ENTIDAD_AGRACTOMEDICO = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "AGRACTOMEDICO";
	public static final String ENTIDAD_AGRACTOMEDICOCABECERA = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "AGRACTOMEDICOCABECERA";
	public static final String ENTIDAD_AGRCAPITATIVOFIJO = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "AGRCAPITATIVOFIJO";
	public static final String ENTIDAD_AGRCAPITATIVOFIJOCABECERA = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "AGRCAPITATIVOFIJOCABECERA";
	public static final String ENTIDAD_AGRCAPITATIVOVARIABLE = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "AGRCAPITATIVOVARIABLE";
	public static final String ENTIDAD_AGRCAPITATIVOVARIABLECABECERA = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "AGRCAPITATIVOVARIABLECABECERA";
	public static final String ENTIDAD_AGRFIJOPORPETICION = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "AGRFIJOPORPETICION";
	public static final String ENTIDAD_AGRFIJOPORPETICIONCABECERA = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "AGRFIJOPORPETICIONCABECERA";
	public static final String ENTIDAD_CANCLAVES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CANCLAVES";
	public static final String ENTIDAD_CANCONTRATOS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CANCONTRATOS";
	public static final String ENTIDAD_CANESTADOS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CANESTADOS";
	public static final String ENTIDAD_CLI_CLIENTES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CLI_CLIENTES";
	public static final String ENTIDAD_CLI_COMPANIAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CLI_COMPANIAS";
	public static final String ENTIDAD_CLI_CONTR_CLIENTES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CLI_CONTR_CLIENTES";
	public static final String ENTIDAD_CLI_EMPRESAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CLI_EMPRESAS";
	public static final String ENTIDAD_CLI_ESTR_CLIENTES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CLI_ESTR_CLIENTES";
	public static final String ENTIDAD_CLI_PACIENTES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CLI_PACIENTES";
	public static final String ENTIDAD_CLI_PREFA_CLIENTES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CLI_PREFA_CLIENTES";
	public static final String ENTIDAD_CLI_PROFESIONALES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CLI_PROFESIONALES";
	public static final String ENTIDAD_CLI_REGLA_CLIENTES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CLI_REGLA_CLIENTES";
	public static final String ENTIDAD_CLI_REMITENTES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CLI_REMITENTES";
	public static final String ENTIDAD_CLI_VISITADOR = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CLI_VISITADOR";
	public static final String ENTIDAD_CONTRATOCAP_ADD = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "CONTRATOCAP_ADD";
	public static final String ENTIDAD_HIER_ACTIVIDAD = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "HIER_ACTIVIDAD";
	public static final String ENTIDAD_HIER_CONTJERAR = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "HIER_CONTJERAR";
	public static final String ENTIDAD_IDENTIFPRUEBAINFORMADA = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "IDENTIFPRUEBAINFORMADA";
	public static final String ENTIDAD_IDENTIFPRUEBATERCEROS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "IDENTIFPRUEBATERCEROS";
	public static final String ENTIDAD_IMPO_CLAVES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "IMPO_CLAVES";
	public static final String ENTIDAD_IMPO_CONTRATOS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "IMPO_CONTRATOS";
	public static final String ENTIDAD_IMPO_ESTADOS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "IMPO_ESTADOS";
	public static final String ENTIDAD_MATCON_ADD = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "MATCON_ADD";
	public static final String ENTIDAD_MOTIVOS_ESTADOS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "MOTIVOS_ESTADOS";
	public static final String ENTIDAD_PERF_DETALLE = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PERF_DETALLE";
	public static final String ENTIDAD_PREFACTURACAPITATIVOVARIABLE = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PREFACTURACAPITATIVOVARIABLE";
	public static final String ENTIDAD_PREFACTURACAPITATIVOVARIABLECABECERA = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PREFACTURACAPITATIVOVARIABLECABECERA";
	public static final String ENTIDAD_PREFACTURADATOSPRODUCTIVOS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PREFACTURADATOSPRODUCTIVOS";
	public static final String ENTIDAD_PREFACTURAINTERLOCUTORES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PREFACTURAINTERLOCUTORES";
	public static final String ENTIDAD_PREFACTURAPRUEBA = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PREFACTURAPRUEBA";
	public static final String ENTIDAD_PREFACTURATRAZABILIDAD = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PREFACTURATRAZABILIDAD";
	public static final String ENTIDAD_PRES_PETICION = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRES_PETICION";
	public static final String ENTIDAD_PRES_PRECIOS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRES_PRECIOS";
	public static final String ENTIDAD_PRES_PRUEBAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRES_PRUEBAS";
	public static final String ENTIDAD_PRIALERTAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRIALERTAS";
	public static final String ENTIDAD_PRICONTROLOPER = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRICONTROLOPER";
	public static final String ENTIDAD_PRIESTADOSECSOL = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRIESTADOSECSOL";
	public static final String ENTIDAD_PRIESTADOSOL = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRIESTADOSOL";
	public static final String ENTIDAD_PRIIMPORTES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRIIMPORTES";
	public static final String ENTIDAD_PRIINTERLOCUTORES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRIINTERLOCUTORES";
	public static final String ENTIDAD_PRIPAGADOR = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRIPAGADOR";
	public static final String ENTIDAD_PRIPRUEBAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRIPRUEBAS";
	public static final String ENTIDAD_PRISOLICITUDES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRISOLICITUDES";
	public static final String ENTIDAD_PRIULTESTADOSECSOL = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRIULTESTADOSECSOL";
	public static final String ENTIDAD_PRIULTESTADOSOL = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRIULTESTADOSOL";
	public static final String ENTIDAD_PRUEBAS_INCONGRUENTES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRUEBAS_INCONGRUENTES";
	public static final String ENTIDAD_PRUEBAS_INCONGRUENTES_ACT = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRUEBAS_INCONGRUENTES_ACT";
	public static final String ENTIDAD_PRUE_ALERTAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRUE_ALERTAS";
	public static final String ENTIDAD_PRUE_CLASIFICACION = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRUE_CLASIFICACION";
	public static final String ENTIDAD_PRUE_ESTADOS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRUE_ESTADOS";
	public static final String ENTIDAD_PRUE_FLUJO = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRUE_FLUJO";
	public static final String ENTIDAD_PRUE_GRUESTADO = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRUE_GRUESTADO";
	public static final String ENTIDAD_PRUE_PRECIO = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRUE_PRECIO";
	public static final String ENTIDAD_PRUE_ULTESTADO = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "PRUE_ULTESTADO";
	public static final String ENTIDAD_REGLAFACADD = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "REGLAFACADD";
	public static final String ENTIDAD_SOLAGRDETALLEPRUEBAINFORMADA = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLAGRDETALLEPRUEBAINFORMADA";
	public static final String ENTIDAD_SOLAGRDETALLEPRUEBATERCEROS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLAGRDETALLEPRUEBATERCEROS";
	public static final String ENTIDAD_SOLI_ALERTAS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_ALERTAS";
	public static final String ENTIDAD_SOLI_CABECERA = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_CABECERA";
	public static final String ENTIDAD_SOLI_CLIENTES_CONT = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_CLIENTES_CONT";
	public static final String ENTIDAD_SOLI_CONTRATO = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_CONTRATO";
	public static final String ENTIDAD_SOLI_DETALLE = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_DETALLE";
	public static final String ENTIDAD_SOLI_ESTADOS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_ESTADOS";
	public static final String ENTIDAD_SOLI_FLUJO = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_FLUJO";
	public static final String ENTIDAD_SOLI_FLUJO_CHILDREN = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_FLUJO_CHILDREN";
	public static final String ENTIDAD_SOLI_FLUJO_LANES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_FLUJO_LANES";
	public static final String ENTIDAD_SOLI_FLUJO_NODES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_FLUJO_NODES";
	public static final String ENTIDAD_SOLI_GRUESTADO = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_GRUESTADO";
	public static final String ENTIDAD_SOLI_INTERLOCUTORES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_INTERLOCUTORES";
	public static final String ENTIDAD_SOLI_MENSAJES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_MENSAJES";
	public static final String ENTIDAD_SOLI_PERFIL = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_PERFIL";
	public static final String ENTIDAD_SOLI_PRODUCTIVOS = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_PRODUCTIVOS";
	public static final String ENTIDAD_SOLI_PRUEBA = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_PRUEBA";
	public static final String ENTIDAD_SOLI_ULTESTADO = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "SOLI_ULTESTADO";
	public static final String ENTIDAD_TRAZ_MESSAGES = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "TRAZ_MESSAGES";
	public static final String ENTIDAD_TRAZ_SOLICITUD = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "TRAZ_SOLICITUD";
	public static final String ENTIDAD_TRAZ_SOLICITUDDET = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "TRAZ_SOLICITUDDET";
	public static final String ENTIDAD_UPDATE_PETCLIENTE = ENTIDAD_VISTA + ENTIDAD_TIPO_GENERICO + "UPDATE_PETCLIENTE";
	
	
}
