INSERT INTO "FACTURACION"."T_MASDATAPROCESSCONTROLSTATUS" VALUES (1,1,'R','Recepcionada',NOW(),1,0,0,NOW(),1);
INSERT INTO "FACTURACION"."T_MASDATAPROCESSCONTROLSTATUS" VALUES (2,1,'T','Transformada',NOW(),1,1,0,NOW(),1);
INSERT INTO "FACTURACION"."T_MASDATAPROCESSCONTROLSTATUS" VALUES (3,1,'S','Simulada',NOW(),1,0,0,NOW(),1);
INSERT INTO "FACTURACION"."T_MASDATAPROCESSCONTROLSTATUS" VALUES (4,1,'C','Clasificada',NOW(),1,0,0,NOW(),1);
INSERT INTO "FACTURACION"."T_MASDATAPROCESSCONTROLSTATUS" VALUES (5,1,'I','Interlocutores',NOW(),1,0,0,NOW(),1);
INSERT INTO "FACTURACION"."T_MASDATAPROCESSCONTROLSTATUS" VALUES (6,1,'A','Agrupada',NOW(),1,0,0,NOW(),2);
INSERT INTO "FACTURACION"."T_MASDATAPROCESSCONTROLSTATUS" VALUES (7,1,'P','Pedido',NOW(),1,0,0,NOW(),2);
INSERT INTO "FACTURACION"."T_MASDATAPROCESSCONTROLSTATUS" VALUES (8,1,'F','Facturada',NOW(),1,1,0,NOW(),2);