INSERT INTO "FACTURACION"."T_SOCIEDADCENTROALMACEN" VALUES (1,'QSGA','QGAT',NOW(),1,0,NOW(),'ECHE');
INSERT INTO "FACTURACION"."T_SOCIEDADCENTROALMACEN" VALUES (2,'L076','L076',NOW(),1,0,NOW(),'LOGO');
INSERT INTO "FACTURACION"."T_SOCIEDADCENTROALMACEN" VALUES (3,'AN72','AN72',NOW(),1,0,NOW(),'ANDO');
INSERT INTO "FACTURACION"."T_SOCIEDADCENTROALMACEN" VALUES (4,'AM73','AM73',NOW(),1,0,NOW(),'AMOR');