INSERT INTO "FACTURACION"."T_MASDATATIPOCONTRATO" VALUES (1,1,NOW(),1,0,NOW(),'Fijo por petición', 'FP');
INSERT INTO "FACTURACION"."T_MASDATATIPOCONTRATO" VALUES (2,1,NOW(),1,0,NOW(),'Capitativo variable', 'CV');
INSERT INTO "FACTURACION"."T_MASDATATIPOCONTRATO" VALUES (3,1,NOW(),1,0,NOW(),'Capitativo Fijo', 'CF');