INSERT INTO "FACTURACION"."T_INCONG_SEC" VALUES (1,1,1,NOW(),1,0,NOW(),1);
INSERT INTO "FACTURACION"."T_INCONG_SEC" VALUES (2,0,1,NOW(),1,0,NOW(),2);
INSERT INTO "FACTURACION"."T_INCONG_SEC" VALUES (3,1,0,NOW(),1,0,NOW(),3);
INSERT INTO "FACTURACION"."T_INCONG_SEC" VALUES (4,0,0,NOW(),1,0,NOW(),4);