INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(1,1,1,'*','FA','Descripcion Alerta',NOW(),1,0,NOW(),'Falta autorización',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(2,1,1,'GC','FD','Descripcion Alerta',NOW(),1,0,NOW(),'Falta documentación',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(3,1,1,'PR','FP','Descripcion Alerta',NOW(),1,0,NOW(),'Falta de pago',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(4,1,1,'*','BP','Descripcion Alerta',NOW(),1,0,NOW(),'Bloquear petición',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(5,1,1,'*','DP','Descripcion Alerta',NOW(),1,0,NOW(),'Faltan datos personales',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(6,1,1,'GC','ED','Descripcion Alerta',NOW(),1,0,NOW(),'Entidad desconocida',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(7,1,1,'GC','EX','Descripcion Alerta',NOW(),1,0,NOW(),'Cargos extras facturacion erróneos',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(8,1,1,'*','FN','Descripcion Alerta',NOW(),1,0,NOW(),'Falta edad y/o fecha de nacimiento',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(9,1,1,'*','FR','Descripcion Alerta',NOW(),1,0,NOW(),'Falta receta',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(10,1,1,'*','ND','Descripcion Alerta',NOW(),1,0,NOW(),'Falta código de prueba',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(11,1,1,'GC','PA','Descripcion Alerta',NOW(),1,0,NOW(),'Petición ampliable según resultados',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(12,1,1,'*','PD','Descripcion Alerta',NOW(),1,0,NOW(),'Prueba desconocida',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(13,1,1,'*','PESO','Descripcion Alerta',NOW(),1,0,NOW(),'Peso obligatorio',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(14,1,1,'*','FM','Descripcion Alerta',NOW(),1,0,NOW(),'Falta muestra',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(15,1,1,'*','CFT','Descripcion Alerta',NOW(),1,0,NOW(),'Falta ttub',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(16,1,1,'*','CMI','Descripcion Alerta',NOW(),1,0,NOW(),'Muestra insuficiente',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(17,1,1,'GC','FMP','Descripcion Alerta',NOW(),1,0,NOW(),'Falta muestra en perfil',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(18,1,1,'*','NCD','Descripcion Alerta',NOW(),1,0,NOW(),'Muestra no conforme drogas',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(19,1,1,'*','NER','Descripcion Alerta',NOW(),1,0,NOW(),'No entregable resultado',1,NULL,NULL);
INSERT INTO "FACTURACION"."T_MASDATAALERTA" VALUES(20,1,1,'*','NM','Descripcion Alerta',NOW(),1,0,NOW(),'Nueva Muestra',1,NULL,NULL);