INSERT INTO "FACTURACION"."T_MASDATAESTADOSGRUPO" VALUES (1, 1, 'NF', 1,NOW(), 1,0, NOW(),'No Facturable');
INSERT INTO "FACTURACION"."T_MASDATAESTADOSGRUPO" VALUES (2, 1, 'FB', 3,NOW(), 1,0, NOW(),'Facturable');
INSERT INTO "FACTURACION"."T_MASDATAESTADOSGRUPO" VALUES (3, 1, 'BLK', 1,NOW(), 1,0, NOW(),'Bloqueada');
INSERT INTO "FACTURACION"."T_MASDATAESTADOSGRUPO" VALUES (4, 1, 'EX', 2,NOW(), 1,0, NOW(),'Excluida');
INSERT INTO "FACTURACION"."T_MASDATAESTADOSGRUPO" VALUES (5, 1, 'ERR', 1,NOW(), 1,0, NOW(),'Errónea');
INSERT INTO "FACTURACION"."T_MASDATAESTADOSGRUPO" VALUES (6, 1, 'F', 3,NOW(), 1,0, NOW(),'Facturada');
INSERT INTO "FACTURACION"."T_MASDATAESTADOSGRUPO" VALUES (7, 1, 'PF', 2,NOW(), 1,0, NOW(),'Pre-Facturada');
INSERT INTO "FACTURACION"."T_MASDATAESTADOSGRUPO" VALUES (8, 1, 'R', 2,NOW(), 1,0, NOW(),'Rectificada');
INSERT INTO "FACTURACION"."T_MASDATAESTADOSGRUPO" VALUES (9, 1, 'PC', 2,NOW(), 1,0, NOW(),'Pedido creado');