INSERT INTO "FACTURACION"."T_MASDATATIPODOCUMENTOSAP" VALUES (1,1,'CREDITMEMOREQUEST','Solicitud de abono',NOW(),1,0,NOW(),null,null);
INSERT INTO "FACTURACION"."T_MASDATATIPODOCUMENTOSAP" VALUES (2,1,'SALESORDER','Pedido de ventas',NOW(),1,0,NOW(),null,null);
INSERT INTO "FACTURACION"."T_MASDATATIPODOCUMENTOSAP" VALUES (3,1,'BILLINGDOCUMENT','Factura de ventas',NOW(),1,0,NOW(),null,null);
INSERT INTO "FACTURACION"."T_MASDATATIPODOCUMENTOSAP" VALUES (4,1,'ACCOUNTINGDOCUMENT','Documento contable',NOW(),1,0,NOW(),null,null);
INSERT INTO "FACTURACION"."T_MASDATATIPODOCUMENTOSAP" VALUES (5,1,'CANCELLATIONBILLINGDOCUMENT','Cancelación factura de ventas',NOW(),1,0,NOW(),null,null);
