INSERT INTO "FACTURACION"."T_MASDATATIPOPETICION" VALUES (1,1,NOW(),1,0,NOW(),'Ambulatorio',1);
INSERT INTO "FACTURACION"."T_MASDATATIPOPETICION" VALUES (2,1,NOW(),1,0,NOW(),'Empresa',2);
INSERT INTO "FACTURACION"."T_MASDATATIPOPETICION" VALUES (3,1,NOW(),1,0,NOW(),'Ingresados',3);
INSERT INTO "FACTURACION"."T_MASDATATIPOPETICION" VALUES (4,1,NOW(),1,0,NOW(),'Est.clínicos',4);
INSERT INTO "FACTURACION"."T_MASDATATIPOPETICION" VALUES (5,1,NOW(),1,0,NOW(),'Industria',5);
INSERT INTO "FACTURACION"."T_MASDATATIPOPETICION" VALUES (6,1,NOW(),1,0,NOW(),'Veterinaria',6);