INSERT INTO "FACTURACION"."T_MASDATASISTEMASLIMS" VALUES (1,1,NOW(),1,0,NOW(),'TrakCare');
INSERT INTO "FACTURACION"."T_MASDATASISTEMASLIMS" VALUES (2,1,NOW(),1,0,NOW(),'Nevis');
INSERT INTO "FACTURACION"."T_MASDATASISTEMASLIMS" VALUES (3,1,NOW(),1,0,NOW(),'Atlas');
INSERT INTO "FACTURACION"."T_MASDATASISTEMASLIMS" VALUES (4,1,NOW(),1,0,NOW(),'NoLabTrak');