package com.echevarne.sap.cloud.facturacion.exception;

public enum EntityType {
		SOLICITUDMUESTREO,
		SOLICITUDINDIVIDUAL,
		SOLICITUDINDIVIDUALITEMS,
		SOLMUESESTADO,
	    PETICIONMUESTREO,
	    PETICIONMUESTREOITEMS,
	    PETMUESINTERLOCUTORES,
	    PETMUESOPERACION,
	    PETMUESALERTA,
	    PETMUESESTADO,
	    PETMUESFECHAS,
	    PETMUESPRECIO,
	    PETMUESPACIENTE,
	    PETMUESMEDICO,
	    PETMUESCLINICOS,
	    PETMUESCONTENEDOR,
	    PETMUESITEMALETTA,
	    PETMUESITEMESTADO,
	    PETMUESITEMPRECIO,
	    MESSAGES,
	    ERRORMESSAGES,
		SIMULACION,
		PRIVADOS
}
