package com.echevarne.sap.cloud.facturacion.odata.annotations.enums;

public enum ValueListEntitiesEnum {
	
	TipoPeticion("TipoPeticionTexts"),
	TipoPeticionString("TipoPeticionStringTexts"),
	TipoContrato("TipoContratoTexts"),
	TipoPosicion("TipoPosicionTexts"),
	TipologiaFacturacion("TipologiaFacturacionTexts"),
	MotivoBloqueo("MotivosBloqueos"),
	MotivoRechazo("MotivoRechazos"),
	MotivoEstado("MotivosEstadoTexts"),
	S4Companies("SociedadesTexts"),
	S4Customers("ClientesTexts"),
	ClientesAll("ClientesAllTexts"),
	Empresas("EmpresasTexts"),
	Companias("CompaniasTexts"),
	Remitentes("RemitentesTexts"),
	Pacientes("PacientesTexts"),
	Profesionales("ProfesionalesTexts"),
	Visitadores("VisitadoresTexts"),
	Interlocutores("InterlocutoresTexts"),
	S4DistributionChannel("CanalDistribucionTexts"),
	S4Division("SectorVentaTexts"),
	S4DivisionPrueba("SectorPruebaTexts"),
	S4SalesOffice("OficinaVentaTexts"),
	S4SalesOrganization("OrganizacionVentaTexts"),
	S4Tarifas("TarifasTexts"),
	S4Regiones("RegionTexts"),
	S4FuncionInterlocutor("FuncionInterlocutorTexts"),
	S4Divisas("DivisasTexts"),
	S4Paises("PaisesTexts"),
	S4Materiales("MaterialesTexts"),
	Contrato("ContratoTexts"),
	Estados("EstadosFacturacionTexts"),
	EstadosTrazabilidad("EstadosTrazabilidadTexts"),
	GrupoEstados("EstadosFacturacionGrupoTexts"),
	MaterialesVenta("MaterialesVentaTexts"),
	ConceptosFacturacion("ConceptosFacturacionTexts"),
	CentrosCoste("CentroCosteTexts"),
	S4Proveedores("ProveedoresTexts"),
	S4Unidades("UnidadesTexts"),
	S4UnidadesProductivas("UnidadesProductivasTexts"),
	S4Impuestos("ImpuestosTexts"),
	Centros("CentroTexts"),
	Almacenes("AlmacenTexts"),
	Peticiones("CodigoPeticionHelps"),
	PeticionesPruebas("PruebasPeticionHelps"),
	CondPreciosPrivados("CondPreciosPrivadosTexts"),
	MuestraRemitida("MuestraRemitidaTexts"),
	EstadoEntidad("EstadoTexts"),
	Boolean("BooleanTexts"),
	TiposCotizacion("TiposCotizacionTexts"),
	Comb("CombTexts"),
	SectoresPrueba("SectorPruebaTexts"),
	Clasificacion("ClasificacionTexts"),
	Descuentos("DescuentoTexts"),
	Periodicidad("PeriodicidadTexts"),
	EstadosPrefactura("EstadoPrefacturaTexts"),
	EstadoEjecucion("EstadoEjecucionTexts"),
	SalesOrganization("OrganizacionVentaNoExitTexts"),
	SalesOffice("OficinaVentaNoExitTexts"),
	ReglaFacturacion("ReglaFacturacionTexts"),
	ProveedoresPrinfoyterceros("ProveedoresPrinfoytercerosTexts"),
	DelegacionProductiva("DelegacionProductivaTexts"),
	DelegacionProductivaAll("DelegacionProductivaAllTexts"),
	TipoDescuento("TipoDescuentoTexts"),
	TipoFacturacion("TipoFacturacionTexts"),
	Alertas("AlertasTexts"),
	ClasificacionLog("ClasificacionLogTexts"),
	ClaseFactura("ClaseFacturaTexts"),
	EstadoFacturacion("EstadoFacturacionTexts"),
	RemitentesProfesionales("RemitentesProfesionalesTexts"),
	TipologiaActividadCobros("TipologiaActividadCobrosTexts"),
	EstadoProcesoActualizacionLog("EstadoActualizacionLogTexts"),
	MaterialesCompra("MaterialesCompraTexts"),
	TiposLiquidacion("TipoLiquidacionTexts"),
	TiposLiquidacionRemProf("TiposLiquidacionTexts"),
	EstadoLiquidacion("EstadoLiquidacionTexts");
	
	public final String entitySet;
	 
    private ValueListEntitiesEnum(String entitySet) {
        this.entitySet = entitySet;
    }
}