
--
-- Transformacion
--
TRUNCATE TABLE "FACTURACION"."T_TRANSFORMACION";
TRUNCATE TABLE "FACTURACION"."T_TRANSFORMACIONCRITERIA";
TRUNCATE TABLE "FACTURACION"."T_TRANSFORMACIONRULE";

--
-- Gestion de estados
--
TRUNCATE TABLE "FACTURACION"."T_MASDATAALERTA";
TRUNCATE TABLE "FACTURACION"."T_MASDATAALERTAPRIVADOS";
TRUNCATE TABLE "FACTURACION"."T_MASDATAALERTA_ALERTAPRIVADOS";
TRUNCATE TABLE "FACTURACION"."T_MASDATACOMBINACIONESTADO";
TRUNCATE TABLE "FACTURACION"."T_MASDATAESTADO";
TRUNCATE TABLE "FACTURACION"."T_MASDATAESTADOSGRUPO";
TRUNCATE TABLE "FACTURACION"."T_MASDATAMOTIVOSESTADO";
TRUNCATE TABLE "FACTURACION"."T_MASDATATRANSICIONESTADO";
TRUNCATE TABLE "FACTURACION"."T_ACCIONESPERMITIDAS";

--
-- Gestion de cambios
--
TRUNCATE TABLE "FACTURACION"."T_ENTITYVERSIONHISTORY";
TRUNCATE TABLE "FACTURACION"."T_GESTIONCAMBIO";
TRUNCATE TABLE "FACTURACION"."T_GESTIONCAMBIODATA";
--
-- Log
--
TRUNCATE TABLE "FACTURACION"."T_LOG";

--
-- Solicitud Muestreo
--
TRUNCATE TABLE "FACTURACION"."T_SOLICITUDMUESTREO";
TRUNCATE TABLE "FACTURACION"."T_SOLMUESESTADO";
TRUNCATE TABLE "FACTURACION"."T_PETICIONPRODADICIONALES";
TRUNCATE TABLE "FACTURACION"."T_PETICIONMUESTREO";
TRUNCATE TABLE "FACTURACION"."T_PETICIONMUESTREOITEMS";
TRUNCATE TABLE "FACTURACION"."T_PETMUESALERTA";
TRUNCATE TABLE "FACTURACION"."T_PETMUESCLINICOS";
TRUNCATE TABLE "FACTURACION"."T_PETMUESCONTENEDOR";
TRUNCATE TABLE "FACTURACION"."T_PETMUESESTADO";
TRUNCATE TABLE "FACTURACION"."T_PETMUESFECHAS";
TRUNCATE TABLE "FACTURACION"."T_PETMUESINTERLOCUTORES";
TRUNCATE TABLE "FACTURACION"."T_PETMUESITEMALERTA";
TRUNCATE TABLE "FACTURACION"."T_PETMUESITEMESTADO";
TRUNCATE TABLE "FACTURACION"."T_PETMUESITEMPRECIO";
TRUNCATE TABLE "FACTURACION"."T_PETMUESITEMSNOMED";
TRUNCATE TABLE "FACTURACION"."T_PETMUESMEDICO";
TRUNCATE TABLE "FACTURACION"."T_PETMUESOPERACION";
TRUNCATE TABLE "FACTURACION"."T_PETMUESPACIENTE";
TRUNCATE TABLE "FACTURACION"."T_PETMUESPRECIO";

--
-- Solicitud Agrupada
--
TRUNCATE TABLE "FACTURACION"."T_SOLICITUDESAGRUPADAS";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRITEMPARTNER";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRITEMPRICING";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRITEMS";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRITEMTEXTS";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPARTNER";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRICING";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRTEXTS";

--
-- Solicitud Individual
--
TRUNCATE TABLE "FACTURACION"."T_SOLICITUDINDIVIDUAL";
TRUNCATE TABLE "FACTURACION"."T_SOLINDITEMPARTNER";
TRUNCATE TABLE "FACTURACION"."T_SOLINDITEMPRICING";
TRUNCATE TABLE "FACTURACION"."T_SOLINDITEMS";
TRUNCATE TABLE "FACTURACION"."T_SOLINDITEMTEXTS";
TRUNCATE TABLE "FACTURACION"."T_SOLINDPARTNER";
TRUNCATE TABLE "FACTURACION"."T_SOLINDPRICING";
TRUNCATE TABLE "FACTURACION"."T_SOLINDTEXTS";

--
-- Trazabilidad
--
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDAD";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADCLASIFICACION";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADSOLESTHISTORY";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADSOLICITUD";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADSOLICITUDAGR";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADESTHISTORY";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADSOLICITUDDOCCONTABLE";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADALBARAN";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADALBESTHISTORY";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADSOLICITUDDOCCONTABLEITEM";
TRUNCATE TABLE "FACTURACION"."T_CONDICIONPRECIOADICIONALITEM";
TRUNCATE TABLE "FACTURACION"."T_CONDICIONPRECIOADICIONALSOLICITUD";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADDOCUMENTOSSAP";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADSOLICITUDPROCESSSTATUS";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADSOLICITUDMESSAGES";
TRUNCATE TABLE "FACTURACION"."T_DATOSPAGADOR";
--
-- Agrupacion
--
TRUNCATE TABLE "FACTURACION"."T_AGRRESULTADO";
TRUNCATE TABLE "FACTURACION"."T_AGRPARAMETROSFACTURACION";
TRUNCATE TABLE "FACTURACION"."T_FACTLOGPERIODOS";
TRUNCATE TABLE "FACTURACION"."T_FACTLOGPROCESO";
TRUNCATE TABLE "FACTURACION"."T_FACTLOGGENERADAS";

--
-- Pruebas informadas y terceros
--
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRUEBAACTIVIDAD";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRUEBAINFORMADA";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRUEBAINFORMADAITEMS";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRUEBATERCEROS";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRUEBATERCEROSITEMS";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRUEBAACTIVIDADLOG";

--
-- MATERIAL CONCEPTO
--
TRUNCATE TABLE "FACTURACION"."T_MATCONCEPTOFACT";

--
-- PRUEBAS INCONGRUENTES
--
TRUNCATE TABLE "FACTURACION"."T_INCONG_COND";
TRUNCATE TABLE "FACTURACION"."T_INCONG_CRIT";
TRUNCATE TABLE "FACTURACION"."T_INCONG_MAT";

--
-- CONVERSIONES
--
TRUNCATE TABLE "FACTURACION"."T_CONVERSIONCENTRO";
TRUNCATE TABLE "FACTURACION"."T_CONVERSIONOFICINAVENTAS";
TRUNCATE TABLE "FACTURACION"."T_CONVERSIONORGANIZACIONVENTAS";
TRUNCATE TABLE "FACTURACION"."T_CONVERSIONSECTOR";
TRUNCATE TABLE "FACTURACION"."T_CONVERSIONSOCIEDAD";

--
-- MENSAJES
--
--
TRUNCATE TABLE "FACTURACION"."T_MESSAGES";
TRUNCATE TABLE "FACTURACION"."T_ERRORMESSAGES";

--
-- CONTRATOS CAPITATIVOS
--
TRUNCATE TABLE "FACTURACION"."T_CONTRATOCAPITATIVOPOLIZAS";
TRUNCATE TABLE "FACTURACION"."T_CONTRATOCAPITATIVOINTERLOCUTORES";
TRUNCATE TABLE "FACTURACION"."T_CONTRATOCAPITATIVO";
TRUNCATE TABLE "FACTURACION"."T_CONTRATOCAPITATIVOTEXT";

--
-- REGLA FACTURACION
--
TRUNCATE TABLE "FACTURACION"."T_REGFACTCLIENTE";
TRUNCATE TABLE "FACTURACION"."T_REGFACTCOMPANIAS";
TRUNCATE TABLE "FACTURACION"."T_REGFACTDELEGACION";
TRUNCATE TABLE "FACTURACION"."T_REGFACTDELEMISORA";
TRUNCATE TABLE "FACTURACION"."T_REGFACTDOCUMENTOUNICO";
TRUNCATE TABLE "FACTURACION"."T_REGFACTEMPRESAS";
TRUNCATE TABLE "FACTURACION"."T_REGFACTOPERACION";
TRUNCATE TABLE "FACTURACION"."T_REGFACTORGVENTA";
TRUNCATE TABLE "FACTURACION"."T_REGFACTPOLIZAS";
TRUNCATE TABLE "FACTURACION"."T_REGFACTPROVREMITENTE";
TRUNCATE TABLE "FACTURACION"."T_REGFACTPRUEBA";
TRUNCATE TABLE "FACTURACION"."T_REGFACTREFERENCIA";
TRUNCATE TABLE "FACTURACION"."T_REGFACTREMITENTES";
TRUNCATE TABLE "FACTURACION"."T_REGFACTSECTOR";
TRUNCATE TABLE "FACTURACION"."T_REGFACTSERVICIOCONC";
TRUNCATE TABLE "FACTURACION"."T_REGFACTTIPOPETICION";
TRUNCATE TABLE "FACTURACION"."T_REGFACTUNIDADPROD";
TRUNCATE TABLE "FACTURACION"."T_REGLAFACTURACION";
TRUNCATE TABLE "FACTURACION"."T_REGLAFACTURAPORFECHA";
TRUNCATE TABLE "FACTURACION"."T_REGFACTCONFIGURACIONDIVISORFACTURA";
--
-- REGLAS
--
TRUNCATE TABLE "FACTURACION"."T_REGLAPREFACTURA";
TRUNCATE TABLE "FACTURACION"."T_FACTURABLEFECHAPETICION";
TRUNCATE TABLE "FACTURACION"."T_BLOQUEOCORTESIA";

--
-- PARAMETRIZACIONES
--
TRUNCATE TABLE "FACTURACION"."T_PARAMETROSGENERALES";
TRUNCATE TABLE "FACTURACION"."T_PARAMGLOBALCLIENTE";
