--
-- Gestion de cambios
--
TRUNCATE TABLE "FACTURACION"."T_ENTITYVERSIONHISTORY";
TRUNCATE TABLE "FACTURACION"."T_GESTIONCAMBIO";
TRUNCATE TABLE "FACTURACION"."T_GESTIONCAMBIODATA";
--
-- Log
--
TRUNCATE TABLE "FACTURACION"."T_LOG";

--
-- Solicitud Muestreo
--
TRUNCATE TABLE "FACTURACION"."T_SOLICITUDMUESTREO";
TRUNCATE TABLE "FACTURACION"."T_SOLMUESESTADO";
TRUNCATE TABLE "FACTURACION"."T_PETICIONPRODADICIONALES";
TRUNCATE TABLE "FACTURACION"."T_PETICIONMUESTREO";
TRUNCATE TABLE "FACTURACION"."T_PETICIONMUESTREOITEMS";
TRUNCATE TABLE "FACTURACION"."T_PETMUESALERTA";
TRUNCATE TABLE "FACTURACION"."T_PETMUESCLINICOS";
TRUNCATE TABLE "FACTURACION"."T_PETMUESCONTENEDOR";
TRUNCATE TABLE "FACTURACION"."T_PETMUESESTADO";
TRUNCATE TABLE "FACTURACION"."T_PETMUESFECHAS";
TRUNCATE TABLE "FACTURACION"."T_PETMUESINTERLOCUTORES";
TRUNCATE TABLE "FACTURACION"."T_PETMUESITEMALERTA";
TRUNCATE TABLE "FACTURACION"."T_PETMUESITEMESTADO";
TRUNCATE TABLE "FACTURACION"."T_PETMUESITEMPRECIO";
TRUNCATE TABLE "FACTURACION"."T_PETMUESITEMSNOMED";
TRUNCATE TABLE "FACTURACION"."T_PETMUESMEDICO";
TRUNCATE TABLE "FACTURACION"."T_PETMUESOPERACION";
TRUNCATE TABLE "FACTURACION"."T_PETMUESPACIENTE";
TRUNCATE TABLE "FACTURACION"."T_PETMUESPRECIO";

--
-- Solicitud Agrupada
--
TRUNCATE TABLE "FACTURACION"."T_SOLICITUDESAGRUPADAS";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRITEMPARTNER";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRITEMPRICING";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRITEMS";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRITEMTEXTS";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPARTNER";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRICING";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRTEXTS";

--
-- Solicitud Individual
--
TRUNCATE TABLE "FACTURACION"."T_SOLICITUDINDIVIDUAL";
TRUNCATE TABLE "FACTURACION"."T_SOLINDITEMPARTNER";
TRUNCATE TABLE "FACTURACION"."T_SOLINDITEMPRICING";
TRUNCATE TABLE "FACTURACION"."T_SOLINDITEMS";
TRUNCATE TABLE "FACTURACION"."T_SOLINDITEMTEXTS";
TRUNCATE TABLE "FACTURACION"."T_SOLINDPARTNER";
TRUNCATE TABLE "FACTURACION"."T_SOLINDPRICING";
TRUNCATE TABLE "FACTURACION"."T_SOLINDTEXTS";

--
-- Trazabilidad
--
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDAD";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADCLASIFICACION";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADSOLESTHISTORY";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADSOLICITUD";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADSOLICITUDAGR";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADESTHISTORY";
TRUNCATE TABLE "FACTURACION"."T_TRZSOLPROCESSSTATUS";
TRUNCATE TABLE "FACTURACION"."T_TRZSOLMESSAGES";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADSOLICITUDDOCCONTABLE";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADALBARAN";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADALBESTHISTORY";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADSOLICITUDDOCCONTABLEITEM";
TRUNCATE TABLE "FACTURACION"."T_CONDICIONPRECIOADICIONALITEM";
TRUNCATE TABLE "FACTURACION"."T_CONDICIONPRECIOADICIONALSOLICITUD";
TRUNCATE TABLE "FACTURACION"."T_TRAZABILIDADDOCUMENTOSSAP";
TRUNCATE TABLE "FACTURACION"."T_DATOSPAGADOR";

--
-- Agrupacion
--
TRUNCATE TABLE "FACTURACION"."T_AGRRESULTADO";
TRUNCATE TABLE "FACTURACION"."T_AGRPARAMETROSFACTURACION";
TRUNCATE TABLE "FACTURACION"."T_FACTPERIODOS";
TRUNCATE TABLE "FACTURACION"."T_FACTLOGPROCESO";
TRUNCATE TABLE "FACTURACION"."T_FACTGENERADAS";

--
-- Pruebas informadas y terceros
--
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRUEBAACTIVIDAD";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRUEBAINFORMADA";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRUEBAINFORMADAITEMS";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRUEBATERCEROS";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRUEBATERCEROSITEMS";
TRUNCATE TABLE "FACTURACION"."T_SOLAGRPRUEBAACTIVIDADLOG";